### ISSUE TITLE
Unknown Locked frame rate ?

### ISSUE THREAD

**Issue by Qskotlv** [DiligentGraphics/DiligentEngine#101]
Curiously, the sample demo suddenly locks framerate to 60FS.
Maybe today I change the clang-format, clean some comment, it's stable today. But it would become 60FPS tomorrow.
Then I revert the code, it becomes normal again.

**Comment by TheMostDiligent** [comment]
What sample?
What rendering backend?
What platform?
What GPU?
(Please fill the issue template, it is there for a reason)

**Comment by Qskotlv** [comment]
Don't mind.
