### ISSUE TITLE
No project() command is present.  The top-level CMakeLists.txt file must   contain a literal, direct call to the project() command

### ISSUE THREAD

**Issue by QuantScientist** [DiligentGraphics/DiligentEngine#102]
Hello,
I am trying to build the library on Windows 10 using VC 19 CMake 3.18 with CLion.

I followed the instructions to the point. The build output is as follows: 
```
f:\Dropbox\Tech\production\ppc\DiligentSamples>cmake -S . -B ./build/Win64 -G "Visual Studio 16 2019" -A x64
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.27.29111.0
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: F:/Dropbox/Tech/production/ppc/DiligentSamples/build/Win64

f:\Dropbox\Tech\production\ppc\DiligentSamples>cmake --build ./build/Win64
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule F:/Dropbox/Tech/production/ppc/DiligentSamples/CMakeLists.txt

f:\Dropbox\Tech\production\ppc\DiligentSamples>

```

I then opened the project in CLIon but there are no targets defined. 

I tried directly building the nuklear UI example, however, the same phenomena happen, no targets appear in the IDE: 
```
No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command
```
Also, I had to comment out:
```
# Create a custom target to run source code formatting validation command
add_format_validation_target(DiligentSamples "${CMAKE_CURRENT_SOURCE_DIR}" DiligentSamples)
```
Which was not found.

**Comment by TheMostDiligent** [comment]
You need to clone and build the DiligentEngine repository, please follow the [instructions here](https://github.com/DiligentGraphics/DiligentEngine#cloning-the-repository)

**Comment by QuantScientist** [comment]
Yes, of course, this is what I initially did. 
There were several errors generated during the build:
![image](https://user-images.githubusercontent.com/18743986/93501983-ceacfd00-f91e-11ea-8778-34e08e79492f.png)

And this is an example of running the samples inside the \DiligentEngine\DiligentSamples folder, the same behaviour as I reported before: 
![image](https://user-images.githubusercontent.com/18743986/93501916-b6d57900-f91e-11ea-8e9c-bcbb4f5ecaaa.png)

**Comment by TheMostDiligent** [comment]
You are running CMake from DiligentSamples folder. It needs to be run from the root folder of the project (see [instructions](https://github.com/DiligentGraphics/DiligentEngine#win32))

**Comment by QuantScientist** [comment]
I did! I first build DiligentEngine and there were still no targets. Then I moved to the  DiligentSamples in an attempt to alleviate this/ 
This was

**Comment by TheMostDiligent** [comment]
Here is the [CMake log](https://ci.appveyor.com/project/DiligentGraphics/diligentengine/build/job/cf63arme3udieo7x?fullLog=true#L65) from the most recent build on CI server.
