### ISSUE TITLE
Doesn't build with musl because build tools are linked with glibc

### ISSUE THREAD

**Issue by Unesty** [DiligentGraphics/DiligentEngine#106]
Build tools must be compiled from source to fix that issue.

**Comment by TheMostDiligent** [comment]
Hi.
Honestly, I am not sure what the issue is. Are you trying to replace glibc with musl when building the engine?

**Comment by Unesty** [comment]
Yes.

**Comment by TheMostDiligent** [comment]
So its only File2String that doesn't build?

**Comment by Unesty** [comment]
Yes.

**Comment by TheMostDiligent** [comment]
What error do you get?

Also, can you fill in the information from the issue template? It is there for a reason.

**Comment by Unesty** [comment]
(Click "Preview" to turn any URL into a clickable link)

If you have build or run problems, please read [troubleshooting](https://github.com/DiligentGraphics/DiligentEngine/blob/master/Troubleshooting.md) first.

Please double-check that your [code is up-to-date, including all submodules](https://github.com/DiligentGraphics/DiligentEngine#cloning-the-repository).

If you have a question that does not require creating an issue, you may ask it on [gitter](https://gitter.im/diligent-engine/Lobby).

For performance issues, please make sure you are running release builds. Debug builds may be significantly slower, especially on Windows.

For GPU-related problems, please make sure you have up-to-date drivers.

Please provide the following information:

Alpine Linux
clang++ 10.0.1, or g++ 10.2.0
ivyBrige mesa 20.2.1-r0
sh: ./File2String: not found

ldd File2String
	/lib64/ld-linux-x86-64.so.2 (0x7feff89fc000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7feff89fc000)
Error relocating File2String: __printf_chk: symbol not found

**Comment by Unesty** [comment]
Another solution is to link this binary statically.

**Comment by TheMostDiligent** [comment]
OK, I see now.
This executable needs to be replaced with a Python script.

**Comment by mgood7123** [comment]
Alpine Linux is musl libc based instead of glibc based, in case you do not know :)

**Comment by logankaser** [comment]
> OK, I see now.
> This executable needs to be replaced with a Python script.

You could also build it from source before building, whatever is easier.

**Comment by TheMostDiligent** [comment]
File2String has been replaced with the python script
