### ISSUE TITLE
Is the light direction inverted in the GLTF Viewer? 

### ISSUE THREAD

**Issue by antonyjones67** [DiligentGraphics/DiligentEngine#108]
Hash 571fb8405d2b7c952b2583eda5ba98f7829db365
Master Branch
Windows 10, Nvidia Geforce 2070
![helmet](https://user-images.githubusercontent.com/3905646/97956847-f50be800-1d66-11eb-8b1e-4854b6ad5259.png)

**Comment by TheMostDiligent** [comment]
The viewer inverts the Y axis of the models when loading, but camera rotation also contributes.
