### ISSUE TITLE
Mingw compilation Error

### ISSUE THREAD

**Issue by BoldHonor** [DiligentGraphics/DiligentEngine#113]
mingw32-make gives this error

D:/Coding Source/game dev portfolio/DiligentEngine/DiligentCore/Graphics/ShaderTools/include/DXCompilerBaseWin32.hpp:30:10: fatal error: atlbase.h: No such file or directory
   30 | #include <atlbase.h>

I am using TDM-GCC 9.2

**Comment by BoldHonor** [comment]
can u help me plzz

**Comment by TheMostDiligent** [comment]
Are you still having issue with the build? You may need to update the Core submodule manually. The main repo still references the old version.

**Comment by BoldHonor** [comment]
thanks I updated the submodule and it worked
