### ISSUE TITLE
The RenderPass demo no work on D3D12 bake-end

### ISSUE THREAD

**Issue by youweibin264905086** [DiligentGraphics/DiligentEngine#115]
I run the RenderPass demo use D3D12 bake-end,  the following error occur on visual studio output window:
Diligent Engine: Info: Max device shader model: 6_4
Diligent Engine: ERROR: Timeout elapsed while waiting for the frame waitable object. This is a strong indication of a synchronization error.
D3D12: Removing Device.
D3D12 ERROR: ID3D12Device::RemoveDevice: Device removal has been triggered for the following reason (DXGI_ERROR_DEVICE_HUNG: The Device took an unreasonable amount of time to execute its commands, or the hardware crashed/hung. As a result, the TDR (Timeout Detection and Recovery) mechanism has been triggered. The current Device Context was executing commands when the hang occurred. The application may want to respawn and fallback to less aggressive use of the display hardware). [ EXECUTION ERROR #232: DEVICE_REMOVAL_PROCESS_AT_FAULT]
Diligent Engine: ERROR: Failed to create dynamic page

- OS and version:  Windows 10.0.18363
- Visual Studio 2017 Debug x64
- Intel I7 1065 G7
- Call stack: 
  >	Tutorial19_RenderPasses.exe!Diligent::Tutorial19_RenderPasses::Render() row 757	C++
 	Tutorial19_RenderPasses.exe!Diligent::SampleApp::Render() row 805	C++
 	Tutorial19_RenderPasses.exe!WinMain(HINSTANCE__ * instance, HINSTANCE__ * __formal, char * __formal, int cmdShow) row 133	C++

- other back-end is ok.

**Comment by TheMostDiligent** [comment]
Are you running this on Intel GPU? Could be driver bug. Do you have the latest drivers?

**Comment by youweibin264905086** [comment]
Yes, running on Intel GPU, it indeed a driver bug, i change m_AdapterType to ADAPTER_TYPE_SOFTWARE, the demo can correctly run.

**Comment by TheMostDiligent** [comment]
OK, closing this for now.
