### ISSUE TITLE
D3D_SIT_RTACCELERATIONSTRUCTURE: Win10 Macro Build Error

### ISSUE THREAD

**Issue by Pentalimbed** [DiligentGraphics/DiligentEngine#116]
I was building the engine with **win10 2004 v19041.685**, cmake and vs2019. I followed the instrustions exactly as is **(git clone --recursive https://github.com/DiligentGraphics/DiligentEngine.git and cmake -S . -B ./build/Win64 -G "Visual Studio 16 2019" -A x64)**. However, when building D3D11/12-static projects there are some errors.

> DiligentCore\Graphics\GraphicsEngineD3DBase\include\ShaderResources.hpp(570,13): error C2065: “D3D_SIT_RTACCELERATIONSTRUCTURE”: unidentified symbol

and the linker can't open Debug\Diligent-GraphicsEngineD3D11-static.lib, Debug\Diligent-GraphicsEngineD3D12-static.lib and ..\..\..\DiligentCore\Graphics\GraphicsEngineD3D11\Debug\GraphicsEngineD3D11_64d.lib. I guess this is because static libraries failed to build. Therefore I commented the ifndef statements in ShaderResources.hpp:

`#ifndef NTDDI_WIN10_19H1 // Defined in Win SDK 19041`
`#    define D3D_SIT_RTACCELERATIONSTRUCTURE (D3D_SIT_UAV_RWSTRUCTURED_WITH_COUNTER + 1)`
`#endif`

and it builds and runs and works. However I'm not sure if that is the right way to do.

**Comment by TheMostDiligent** [comment]
What Windows SDK version are you using?

**Comment by Pentalimbed** [comment]
> What Windows SDK version are you using?

Could it be different from my Windows version? Unfortunately I'm out for a long while so I can't really check it, but my VS should be up to date and the project files are auto-generated.

**Comment by azhirnov** [comment]
Pentalimbed, check "Windows SDK version" in project properties.
To update Windows SDK you should run visual studio installer and select latest windowns sdk component.

I have same issue in 10.0.18362.0, NTDDI_WIN10_19H1 is defined but D3D_SIT_RTACCELERATIONSTRUCTURE is not.
