### ISSUE TITLE
Engine zip download is not complete

### ISSUE THREAD

**Issue by janhec** [DiligentGraphics/DiligentEngine#117]
https://github.com/DiligentGraphics/DiligentEngine:
The folders appear empty, e.g. DiligentEngine-master.zip\DiligentEngine-master\DiligentCore\
This appears to have been the case from at least september last year.
Windows 10, using either 7zip or (windows file) explorer.

**Comment by TheMostDiligent** [comment]
I added the source code archive to the [latest release](https://github.com/DiligentGraphics/DiligentEngine/releases/tag/v2.4.g).
If you are trying to download the latest source code using the Download Zip link from GitHub, the archive will not contain the submodules. This is just how GitHub works.
