### ISSUE TITLE
Windows 7 build: samples requires XINPUT1_4.dll

### ISSUE THREAD

**Issue by Pentalimbed** [DiligentGraphics/DiligentEngine#118]
OS: windows 7 v6.1 build 7001
SDK: 10.0.18362.0

Using default cmake arguments.

All samples but HelloWin32 request XINPUT 1.4 when running, which is only available on windows 8 and after.

**Comment by TheMostDiligent** [comment]
This looks to be [dear imgui](https://github.com/ocornut/imgui) issue. Can you try to download and build imgui only to see if their examples run?

**Comment by Pentalimbed** [comment]
imgui test result:

- glfw and sdl examples are all ok
- win32 examples with any version of dx requires XINPUT

**Comment by TheMostDiligent** [comment]
[It looks like](https://github.com/DiligentGraphics/imgui/blob/master/examples/imgui_impl_win32.cpp#L18) you need to define `IMGUI_IMPL_WIN32_DISABLE_LINKING_XINPUT` to make imgui work on Win7

**Comment by TheMostDiligent** [comment]
@Pentalimbed Can you try to modify [this line](https://github.com/DiligentGraphics/imgui/blob/0eadb0092027f33e463943e62e9353dec7582efe/examples/imgui_impl_win32.cpp#L24) as follows:

```cpp
#if defined(_MSC_VER) && (_WIN32_WINNT >= _WIN32_WINNT_WIN8) && !defined(IMGUI_IMPL_WIN32_DISABLE_LINKING_XINPUT)
```

**Comment by Pentalimbed** [comment]
Defining IMGUI_IMPL_WIN32_DISABLE_GAMEPAD in project setting and rebuilding works for imgui examples. Only defining IMGUI_IMPL_WIN32_DISABLE_LINKING_XINPUT causes linking error.

Diligent's examples doesn't work no matter how.

**Comment by TheMostDiligent** [comment]
Did you try the fix I suggested above?

**Comment by Pentalimbed** [comment]
Yes, here's the snippet from '_(path)_\DiligentEngine\DiligentTools\ThirdParty\imgui\examples\imgui_impl_win32.cpp':

```// Using XInput library for gamepad (with recent Windows SDK this may leads to executables which won't run on Windows 7)
#ifndef IMGUI_IMPL_WIN32_DISABLE_GAMEPAD
#include <XInput.h>
#else`
#define IMGUI_IMPL_WIN32_DISABLE_LINKING_XINPUT
#endif
#if defined(_MSC_VER) && (_WIN32_WINNT >= _WIN32_WINNT_WIN8) && !defined(IMGUI_IMPL_WIN32_DISABLE_LINKING_XINPUT)
#pragma comment(lib, "xinput")
//#pragma comment(lib, "Xinput9_1_0")
#endif
```

and with or without other macros defined in project setting, it still asks me for xinput 1.4.

**Comment by TheMostDiligent** [comment]
> Defining IMGUI_IMPL_WIN32_DISABLE_GAMEPAD in project setting and rebuilding works for imgui examples..

How do you define this for Diligent? Maybe try uncommenting those defines in `imgui_impl_win32.h`? I can't think of any other place where xinput.lib may be referenced.

**Comment by Pentalimbed** [comment]
What I did with imgui is:

- nothing changed in imgui_impl_win32.cpp
- nothing changed in any of the example source files
- in **example_win32_directx11** -> **project setting** -> **c/c++** -> **preprocessor** -> **preprocessor definition**, adding IMGUI_IMPL_WIN32_DISABLE_GAMEPAD and IMGUI_IMPL_WIN32_DISABLE_LINKING_XINPUT
- rebuild the example project, run and done.

The same doesn't apply to diligent example projects. Could it be that diligent's version of imgui are outdated?

**Comment by Pentalimbed** [comment]
Okay, so I explicitly added definition to imgui_impl_win32.cpp. Now it runs. Sorry for the trouble.
