### ISSUE TITLE
Formatted or structured buffers require actual Vulkan backing resource and cannot be suballocated from dynamic heap

### ISSUE THREAD

**Issue by 9MW** [DiligentGraphics/DiligentEngine#122]
(Formatted or structured buffers require actual Vulkan backing resource and cannot be suballocated from dynamic heap. In current implementation, the entire contents of the backing buffer is updated when the buffer is unmapped. As a consequence, the buffer cannot be mapped with MAP_FLAG_NO_OVERWRITE flag because updating the whole buffer will overwrite regions that may still be in use by the GPU.

Any clue to implement this on vulkan?

**Comment by TheMostDiligent** [comment]
Formatted or structured buffers should be updated with UpdateBuffer method

**Comment by TheMostDiligent** [comment]
Dynamic structured buffers have been refactored and now work similar to constant buffers. Formatted buffers though still require backing resource - there is no other way to implement them.
