### ISSUE TITLE
Tutorials "Mesh Shader" and "RayTracing" don't work with Vulkan  

### ISSUE THREAD

**Issue by ilyachastikov** [DiligentGraphics/DiligentEngine#123]
Hello. I've tried to build and run all tutorials in latest 2.4g version and faced with such problem: 
Tutorials "Mesh Shader" and "RayTracing" work fine with Direct3D12, but with Vulkan its crashes with messages: 
"Debug Assertion failed in 
Diligent::GLSLangUtils::HLSLtoSPIRV(), file GLSLangUtils.cpp
line 461:
Mesh shaders are not supported, use DXCompiler to
build SPIRV from HLSL"  - for Mesh Shader Tutorial,
"Debug Assertion failed in 
Diligent::GLSLangUtils::HLSLtoSPIRV(), file GLSLangUtils.cpp
line 459:
RayTracing shaders are not supported, use DXCompiler to
build SPIRV from HLSL"  - for RayTracing Tutorial.
I've used latest drivers 461.09. All other tutorials work fine with Vulkan.

**Comment by azhirnov** [comment]
glslang can't compile HLSL with shader model 6.0+ and engine can't find DXCompiler for SPIRV.
Solutions:
1. install latest Vulkan SDK and rerun cmake, you should see message "Found DXCompiler for Vulkan"
2. download artifacts from DXC CI [here](https://ci.appveyor.com/project/antiagainst/directxshadercompiler/branch/master/job/fxn40ymbah1g7frh/artifacts), rename dxcompiler.dll to spv_dxcompiler.dll and put it to binary diretrory for sample.

**Comment by ilyachastikov** [comment]
Now all works. Thank you.
