### ISSUE TITLE
how to use libopencv_java.so file in android unityplugin i need help ... 

### ISSUE THREAD

**Issue by minsoo5403** [DiligentGraphics/DiligentEngine#127]
First of all, thank you for making a great open source.

I successfully built and tested the Unity Plugin for Android, but the following error occurs while working to include OpenCV in Android.

libopencv_java3.so: error adding symbols: File in wrong format

The software versions I used are as follows..
Ubuntu 18.04.5
CMake 3.19.7
GCC-7.5
OpenCV 3.4.0

What I added are the header files of OpenCV and two files, libopencv_java.so / libopencv_java3.so.

Should I build a new plugin for OpenCV Android?? OpenCV is version 3.4.0, and we have confirmed that the example APK works well...

Please i need Help.

I modified unityplugin/GhostCubeScene/CMakeList.txt as below.

# Connect directory like this
target_include_directories(GhostCubeScene
PRIVATE
    ../GhostCubePlugin/PluginSource/src/Unity
    src
    src/opencv/include
    src/opencv/include/opencv
    src/opencv/include/opencv2
)

# Add .so file path via
add_library(libopencv_java3 SHARED IMPORTED)
add_library(libopencv_java SHARED IMPORTED)
set_target_properties(libopencv_java3 PROPERTIES IMPORTED_LOCATION "/home/k/work/DiligentEngine/unityplugin/GhostCubeScene/src/jniLibs/armeabi-v7a/libopencv_java3.so")
set_target_properties(libopencv_java PROPERTIES IMPORTED_LOCATION "/home/k/work/DiligentEngine/unityplugin/GhostCubeScene/src/jniLibs/armeabi-v7a/libopencv_java.so")

# Connect like this
target_link_libraries(GhostCubeScene
PRIVATE
    Diligent-BuildSettings
    Diligent-NativeAppBase
    UnityEmulator
    Diligent-TargetPlatform
    libopencv_java3
    libopencv_java
)

I don't know if these methods can work. Or do I have to do the correction elsewhere??

I wonder if it should be done inside 'add_target_platform_app(GhostCubeScene "${SOURCE}" "${INCLUDE}" "${ALL_ASSETS}")'.

**Comment by TheMostDiligent** [comment]
I can't really advise on this problem as I haven't used Open CV. This is problem is not related to Diligent Engine and I would suggest asking the question on forums related to OpenCV.
