### ISSUE TITLE
ATL support 

### ISSUE THREAD

**Issue by tjysdsg** [DiligentGraphics/DiligentEngine#13]
When using Visual Studio 2017, Visual C++ ATL Support should be installed via Visual Studio Installer.
Should be added to readme.md:)

**Comment by DiligentGraphics** [comment]
Thanks for pointing this out!
Fixed https://github.com/DiligentGraphics/DiligentEngine/commit/ac82b22fff555fdbf7cdcbefa95f2939eec2104d
