### ISSUE TITLE
Raytracing tutorial on RX 6800 with Vulkan

### ISSUE THREAD

**Issue by urcereal** [DiligentGraphics/DiligentEngine#131]
Hi,

Get an error when running the Tutorial21_RayTracing exe with Vulkan backend. Works fine when running with DX12 backend. 

Windows 10 Pro, 2004. Ryzen 5600 CPU, RX 6800 GPU using 21.3.2 driver.

[objdump.txt](https://github.com/DiligentGraphics/DiligentEngine/files/6275194/objdump.txt)

Diligent Engine: ERROR: Debug assertion failed in Diligent::DeviceContextVkImpl::BuildBLAS(), file DeviceContextVkImpl.cpp, line 3055:
AABB start address is not properly aligned

cmake -S . -B ./build/Win64 -G "Visual Studio 16 2019" -A x64
-- The C compiler identification is MSVC 19.28.29913.0
-- The CXX compiler identification is MSVC 19.28.29913.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is not specified, default to Debug. Note that this is only relevant for single-configuration generators (such as Makefile Generators and Ninja).
Target platform: Win32. SDK Version: 10.0.19041
D3D11_SUPPORTED:  TRUE
D3D12_SUPPORTED:  TRUE
GL_SUPPORTED:     TRUE
GLES_SUPPORTED:   FALSE
VULKAN_SUPPORTED: TRUE
METAL_SUPPORTED:  FALSE
-- Found PythonInterp: C:/Users/xxxxxxx/AppData/Local/Programs/Python/Python39/python.exe (found suitable version "3.9.4", minimum required is "3")
-- Using Debug VC++ CRT: MDd
-- Using Release VC++ CRT: MD
-- Using MinSizeRel VC++ CRT: MD
-- Using RelWithDebInfo VC++ CRT: MD
-- Using Debug VC++ CRT: MDd
-- optimizer enabled
-- SPIRV-Cross: Finding Git version for SPIRV-Cross.
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.30.0.windows.1")
-- SPIRV-Cross: Git hash: cd9d97b8
-- Found Vulkan: C:/VulkanSDK/1.2.170.0/Lib/vulkan-1.lib
-- Found DXCompiler for Vulkan
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Using Win32 for window creation
-- Configuring done
-- Generating done

**Comment by azhirnov** [comment]
Will fix it.
Try release configuration, it disables asserts and validation layers, driver may works even if some parameters does not match the requirements of the Vulkan specifications.

**Comment by azhirnov** [comment]
On AMD Vulkan driver supports only 1 recursion depth (maxRayRecursionDepth = 1), when DirectX 12 supports 31 recursion depth. So this sample can not draw shadows, reflections and refractions on vulkan backend.

I added a possible fix for this bug in [commit](https://github.com/DiligentGraphics/DiligentCore/commit/e794434030c86332f7d02abd6ec41c0482c7cf11), make full rebuild for sample to make sure that DLL with vulkan backend copied to the sample binary directory.

It is look like on AMD required memory alignment for buffer is smaller than 8 bytes.
The another assumption is that Vulkan spec does not guarantee that device address have the same alignment as a buffer memory alignment and we need to align address after buffer creation.

**Comment by urcereal** [comment]
Hi azhirnov,

Yep, fixes the crash but as you've mentioned the sample cannot draw shadows, reflections and refractions.

Thanks for the swift response.
