### ISSUE TITLE
ram usage of 31+GB normal ?

### ISSUE THREAD

**Issue by ZweiEuro** [DiligentGraphics/DiligentEngine#135]
Hi,
Sorry if this is a stupid question, but my compilation crashed because I ran out of ram (16GB) so I switched to a bigger machine (I just wanted to start so I wanted to build the samples)
This also failed, is it normal that building the engine eats over 31GB of RAM ?

Or is something wrong with my configuration that causes this ?

**Comment by TheMostDiligent** [comment]
Which platform are you building on/for? (The issue template asks you to answer these questions for a reason).
Are you talking about hard drive space or RAM?

**Comment by ZweiEuro** [comment]
nevermind i am dumb, i used -j, it builds sub 2GB without it
