### ISSUE TITLE
Raytracing tutorial shows white window when choosing vulkan.

### ISSUE THREAD

**Issue by DaOnlyOwner** [DiligentGraphics/DiligentEngine#136]
Hello,

as the title says, the Vulkan backend just shows a white window, DirectX works as intended. I have a RTX 2080. Is it intended that Vulkan doesn't work? 

Greetings,
DaOnlyOwner

**Comment by TheMostDiligent** [comment]
Please fill in the issue template.
There are good reasons it asks for information about your platform/driver/output etc.

**Comment by DaOnlyOwner** [comment]
Okay, here you go:

- OS Version: Windows 10.0.19042
- Visual Studio 2019 Debug x64 + CMake 3.20.2
- RTX 2080, API Version: 1.2.142, Driver version: 457.120.0
Debug messages:
Diligent Engine: Info: Using physical device 'GeForce RTX 2080', API version 1.2.142, Driver version 457.120.0.
Diligent Engine: ERROR in Diligent::EngineFactoryVkImpl::CreateDeviceAndContextsVk::<lambda_1f778d9a38528e119851ed2e5c8df9bb>::operator ()() (EngineFactoryVk.cpp, 198): Ray tracing is not supported by this device
Ausnahme ausgelöst bei 0x00007FFA58F44B59 in Tutorial21_RayTracing.exe: Microsoft C++-Ausnahme: std::runtime_error bei Speicherort 0x0000009942CFEA30.
Diligent Engine: ERROR in Diligent::SampleApp::InitializeDiligentEngine() (SampleApp.cpp, 304): Unable to initialize Diligent Engine in Vulkan mode. The API may not be available, or required features may not be supported by this GPU/driver/OS version.
Ausnahme ausgelöst bei 0x00007FFA58F44B59 in Tutorial21_RayTracing.exe: Microsoft C++-Ausnahme: std::runtime_error bei Speicherort 0x0000009942CFF4B0.
Diligent Engine: ERROR in Diligent::SampleAppWin32::OnWindowCreated() (SampleAppWin32.cpp, 200): Failed to initialize Diligent Engine.

**Comment by TheMostDiligent** [comment]
This is strange. For some reason it detects that ray tracing in Vulkan is not supported:

```
Diligent Engine: ERROR in Diligent::EngineFactoryVkImpl::CreateDeviceAndContextsVk::<lambda_1f778d9a38528e119851ed2e5c8df9bb>::operator ()() (EngineFactoryVk.cpp, 198): Ray tracing is not supported by this device
```

This is odd as your driver is up-to-date.

**Comment by DaOnlyOwner** [comment]
Yeah that's odd. I updated my driver and now it fails with an assertion: 
![grafik](https://user-images.githubusercontent.com/11295581/116824286-ad391280-ab89-11eb-904f-2842ec08ec89.png)

**Comment by TheMostDiligent** [comment]
You need to install [Vulkan SDK](https://vulkan.lunarg.com/sdk/home#windows).
Ray tracing HLSL shaders can only be compiled to SPIRV using new DirectX compiler that is not bundled with the engine by default.
Clear CMake cache and re-generate solution files after you install the SDK. The engine will find it and use for HLSL ray tracing shaders.

**Comment by DaOnlyOwner** [comment]
I installed the Vulkan SDK ( I have the newest version installed). It somehow still doesn't work.

**Comment by TheMostDiligent** [comment]
Did you re-generate your project files? In your CMake you should see this:

```
1>-- SPIRV-Cross: Finding Git version for SPIRV-Cross.
1>-- SPIRV-Cross: Git hash: cd9d97b8
1>-- Found DXCompiler for Vulkan
```

**Comment by DaOnlyOwner** [comment]
Ah that could be it. It doesn't find Vulkan: 
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)
Why doesn't it find it even though I have installed the SDK?
The other tutorials work with Vulkan tho.

**Comment by TheMostDiligent** [comment]
> Why doesn't it find it even though I have installed the SDK?

Did you clear CMake cache or re-generated the project files after installing the SDK?

Do you have `VULKAN_SDK` environment variable? It should be set by the installer.

> The other tutorials work with Vulkan tho.

DirectX compiler is only required to compile ray tracing (and mesh) shaders from HLSL to SPIRV. Other tutorials/samples don't need it.

**Comment by DaOnlyOwner** [comment]
Yes I cleared the cash, it made no difference. The environment variable is set to the correct path. I don't know why it cannot find the vulkan sdk...

**Comment by DaOnlyOwner** [comment]
Okay I found the issue. The environment variable was not correctly set. Now it works ;)
