### ISSUE TITLE
Can we have a simple hello word compute shader example?

### ISSUE THREAD

**Issue by trsh** [DiligentGraphics/DiligentEngine#138]
The current one in tutorials is huge and complicated and hard for beginners to understand where even start to look.

**Comment by TheMostDiligent** [comment]
> The current one in tutorials is huge

The tutorial source file is only 440 lines. I doubt it is possible to make anything meaningful in fewer lines.

Diligent Engine tutorials are intended to demonstrate how to use the API. There is a lot of information on compute shaders on the web and there is no point in duplicating it.
