### ISSUE TITLE
Can't build with Ninja: cyclic dependency through HLSLDefinitions_inc.fxh

### ISSUE THREAD

**Issue by MikeLankamp** [DiligentGraphics/DiligentEngine#139]
### Environment
- Windows 10
- Visual Studio 2019 16.9.4 (MSVC 19.28.29914.0)
- CMake 3.17.3
- Ninja 1.7.2
- Git 2.26.0.windows.1

###  Reproduction
1. Open the "x64 Native Tools Command Prompt for VS 2019"
2. Clone a fresh repo
```
git clone --recursive https://github.com/DiligentGraphics/DiligentCore.git
cd DiligentCore
```
3. Run CMake with the "Ninja" generator and build:
```
mkdir build
cmake -G Ninja -S . -B build
cmake --build build
```
4. Ninja complains about a cyclic dependency via a generated HLSL header:
```
ninja: error: dependency cycle: ../Graphics/GraphicsEngineD3DBase/include/HLSLDefinitions_inc.fxh -> Graphics/ShaderTools/Diligent-ShaderTools.lib -> Graphics/ShaderTools/CMakeFiles/Diligent-ShaderTools.dir/src/HLSLUtils.cpp.obj -> ../Graphics/GraphicsEngineD3DBase/include/HLSLDefinitions_inc.fxh
```

**This prevents using Ninja to build Diligent**.

The Visual Studio generator does not suffer from this, but that generator does not support creating `compile_commands.json` for static code analysis of my project with `clang-tidy`.

---

It seems that the generated `HLSLDefinitions_inc.fxh` is attached to the `Diligent-GraphicsEngineD3DBase` target in whose `CMakeLists.txt` its custom command is defined. That target in turn depends on `Diligent-ShaderTools`, which includes `HLSLUtils.cpp`, which `#includes` `HLSLDefinitions_inc.fxh`, completing the cycle.

One option might be to turn the generated `HLSLDefinitions_inc.fxh` into its own target so it doesn't get attached to `Diligent-GraphicsEngineD3DBase`. Of course, from a modularity point of view, the ShaderTools component including something from the GraphicsEngineD3DBase component isn't too nice if GraphicsEngineD3DBase also depends on ShaderTools.

**Comment by TheMostDiligent** [comment]
`HLSLDefinitions_inc.fxh` was moved at some point from `Diligent-GraphicsEngineD3DBase` to `Diligent-ShaderTools`, but apparently the build rule remained in `Diligent-GraphicsEngineD3DBase`. Will take a look.

Note that there were other problems with ninja and it is not an officially supported build method.

**Comment by MikeLankamp** [comment]
> Note that there were other problems with ninja and it is not an officially supported build method.

Hm, that's a shame, because it makes it harder to use tools like clang-tidy on any project that includes Diligent, Technically one could just run `cmake -G Ninja` without building to get `compile_commands.json`, but that requires a separate step and build folder.

Either way, I appreciate anything that can be done to help fix this!

**Comment by mgood7123** [comment]
do note that "Makefile" generators (and probably others) will "drop" dependency cycles if detected

for example, when building `libcurl` with `-G "Unix Makefiles"`

`make[2]: Circular docs/curl-config.1 <- docs/curl-config.1 dependency dropped.`
`make[2]: Circular docs/mk-ca-bundle.1 <- docs/mk-ca-bundle.1 dependency dropped.`

in `-G Ninja` this will generate an error due to such cyclic dependency not being dropped
