### ISSUE TITLE
Add conan support

### ISSUE THREAD

**Issue by AndreyMlashkin** [DiligentGraphics/DiligentEngine#146]
Conan is a Package and Dependency Manager. It is a convenient tool to manage multiple dependencies.
It would be great to have a possibility to use DiligentEngine as a conan recipe.
https://github.com/conan-io/conan-center-index/issues/1533

**Comment by TheMostDiligent** [comment]
@AndreyMlashkin FYI, I've made a set of changes to make dependencies more flexible, take a look at #40.
This does not change the default build system, but allows all third-party libraries to be defined outside of Diligent.

**Comment by TheMostDiligent** [comment]
Ideally, there will be no need in [patches](https://github.com/conan-io/conan-center-index/tree/master/recipes/diligent-core/all/patches) as CMake should be able to pick up any existing third-party libs and use them instead of submodules.

**Comment by AndreyMlashkin** [comment]
@TheMostDiligent, in v2.5.2 it works really good for all libraries but glslang, there we have

CMake Error at source_subfolder/ThirdParty/CMakeLists.txt:68 (add_subdirectory):

**Comment by AndreyMlashkin** [comment]
-    if (NOT ${DILIGENT_NO_GLSLANG} AND (NOT TARGET glslang))
+    if (NOT ${DILIGENT_NO_GLSLANG} AND (NOT TARGET glslang::glslang))
This fixes my problem
