### ISSUE TITLE
Emscripten support?

### ISSUE THREAD

**Issue by mctb32** [DiligentGraphics/DiligentEngine#15]
Is it possible and do you have any plans to support the emscripten platform in Diligent? I believe this is what Unity/Unreal Engine/BGFX use to target HTML5/asm.js, which is a very nice feature.

http://kripken.github.io/emscripten-site/

Also, you could use it to allow running samples directly on the Diligent website :)

**Comment by DiligentGraphics** [comment]
Looks like emscripten supports OpenGLES3.0, so this should be possible. Not all features will be available on the Web (such as multithreaded command recording), but it should work.

**Comment by jayrulez** [comment]
@DiligentGraphics are you still looking into supporting webgl2?

**Comment by DiligentGraphics** [comment]
Yes, it is still in plans but at this point unfortunately there is no bandwidth for this.

**Comment by ivalylo** [comment]
It probably makes more sense to look forward to WebGPU and how this would map to webassembly.

**Comment by adamikandras** [comment]
Please make it happen!
I noticed that there are some related cmake parameters in the config, but couldn't succeed with the emscripten build.
I think the whole engine would greatly benefit from becoming compatible with emscripten and it would make it much more desirable for indie developers, who want to showcase/demo their work on the web.
I was thinking of a github action, that would deploy the latest version of the pushed/merged code to a website, so I can see and try it anytime on the web from anywhere.
It would make game development such a great fun!

**Comment by daboss3d** [comment]
That would be very interesting, specially if the engine as a small footprint, it will be perfect for web.
Not only for games, but for a lot of other applications.
Let's hope WebGPU be available soon :)

**Comment by crlf0710** [comment]
I did some research into porting DiligentCore to support Emscripten. Currently the compilation succeeds and the remaining issue is that it needs a few GL ES 3.1 APIs that is not supported by even WebGL 2.0.
First is a group of APIs originated as `OpenGL.GL.EXT.separate_shader_objects`:
```text
glBindProgramPipeline
glDeleteProgramPipelines
glGenProgramPipelines
glUseProgramStages
```
Second is an API called `glGetTexLevelParameteriv`. The code use conditional compilation to avoid using it if it is not supported, but the condition doesn't reflect the actual status of Emscripten. This can be fixed easily.

I'm not sure how to avoid the previous group of APIs. Could someone give me hint on how to workaround these usages?

**Comment by crlf0710** [comment]
Oh never mind, it seems they're only used when the `SeparablePrograms` device feature is enabled. Not a big deal.

**Comment by seanisom** [comment]
@crlf0710 do you have a fork / branch that you can share with any cmake changes necessary to build under emscripten using WebGL? I'm very interested in this as well.

**Comment by crlf0710** [comment]
@seanisom I need to get my branch audited according to some corporate regulation before i can share it to github. I'll try to do so after i finish the `SeparablePrograms` modifications mentioned above.

**Comment by crlf0710** [comment]
status update: i've mostly get DiligentCore on webgl program working, modulo [a bug in emscripten itself](https://github.com/emscripten-core/emscripten/issues/13808). I'll make a workaround for this outside the scope of DiligentCore. Hopefully i'll get everything ready soon.

**Comment by TheMostDiligent** [comment]
@crlf0710 Would you be able to share your branch?

**Comment by crlf0710** [comment]
@TheMostDiligent I think so, though it'll need several days before i'm granted i think.

**Comment by crlf-code** [comment]
Submitted as DiligentCore `PR #197`
