### ISSUE TITLE
Building with Metal Support - Where is DiligentCorePro?

### ISSUE THREAD

**Issue by luigi-rosso** [DiligentGraphics/DiligentEngine#152]
Wonderful work on this project. We're experimenting with this over at https://rive.app.

I'm trying to build with support for Metal (direct, not via MoltenVK) but running CMAKE on my Mac gives the following error:
```
Target Platform: MacOS
DiligentCorePro module is not found. Metal backend will be disabled
D3D11_SUPPORTED:  FALSE
D3D12_SUPPORTED:  FALSE
GL_SUPPORTED:     TRUE
GLES_SUPPORTED:   FALSE
VULKAN_SUPPORTED: TRUE
METAL_SUPPORTED:  FALSE
```

Looks like it's looking for a DiligentCorePro folder which isn't provided. Is this now a paid for feature or has direct Metal support been removed?

**Comment by TheMostDiligent** [comment]
Yes, native Metal support is a premium feature that is only available for commercial clients.

**Comment by luigi-rosso** [comment]
Thank you.
