### ISSUE TITLE
Importing a depth texture with RenderDeviceD3D11::CreateTexture2DFromD3DResource

### ISSUE THREAD

**Issue by JoeLudwig** [DiligentGraphics/DiligentEngine#154]
I'm working on a hello world example to use DiligentEngine to render to a VR headset via OpenXR: https://github.com/JoeLudwig/diligent_hello_openxr

Under OpenXR textures (including color and depth) need to be created by the OpenXR runtime. For the color textures I'm using CreateTexture2DFromD3DResource to create the corresponding DiligentEngine resource. For the depth textures that doesn't work because they don't end up with the right bind flags.

I'm happy to work up a pull request to address this, but since there are a few options I thought it was worth raising an issue first. I can see a couple general approaches:
* Don't change the engine at all and use CreateDeviceObject directly in the application (assuming I can access it.) These import helpers aren't very long, after all...
* Add an optional bind flags argument to all of the CreateTexture*FromD3DResource functions. Have the default stay the same as what it is right now.
* Add an optional TextureDesc argument to all of the CreateTexture*FromD3DResource functions. Have it use the same defaults it does now, which is just whatever is in the defaults for TextureDesc structures.
* Add a new helper CreateDepthTextureFromD3DResource

What do you think? Would you be interested in this sort of pull request?

**Comment by TheMostDiligent** [comment]
Hi!
What bind flags are missing for the depth texture?

**Comment by TheMostDiligent** [comment]
I double-checked out unit tests, and for `D32_FLOAT` it correctly recovers `BIND_DEPTH_STENCIL` bind flag from the native texture

**Comment by JoeLudwig** [comment]
Maybe I'm misinterpreting what I'm seeing:
![image](https://user-images.githubusercontent.com/303656/125971647-08ddd440-f07a-4442-823d-23b3a7676b34.png)

Perhaps SteamVR isn't creating the texture with the right flags when it makes the underlying texture?

**Comment by TheMostDiligent** [comment]
Are you sure this is a depth texture? From its name it looks like it should be a render target, not depth stencil.

**Comment by JoeLudwig** [comment]
I had a copy-paste bug and was reading the color swapchain twice instead of reading the depth swapchain. Nothing to see here.

Thanks for your help!  I'll probably be back when the time comes to get Vulkan working (because OpenXR involves the runtime being the one to call vkCreateInstance, which I'm not sure there's a way to do in DiligentEngine yet.)
