### ISSUE TITLE
OpenGL ES 2.0 support

### ISSUE THREAD

**Issue by sazlang** [DiligentGraphics/DiligentEngine#16]
Are you planning to add OpenGL ES 2.0 support in the near future?
Note: 23.8% percent of the android devices don't support 3.0 .

**Comment by DiligentGraphics** [comment]
One of the key features of Diligent Engine is that it allows using HLSL on all supported platforms and backends. GLES2.0 shading language misses a number of critical features that does not make shader translation possible.

**Comment by eugeneko** [comment]
@DiligentGraphics 
Just curious, what are actual issues with OpenGL ES 2.0 support?
Maybe if you give some hints and directions, there would be people ready to try porting.
OpenGL ES 2.0 and especially WebGL 1.0 are still quite popular.

**Comment by DiligentGraphics** [comment]
@eugeneko The main problem was with shader conversion. HLSL->GLSL converter relies on specifying variable locations to match shader inputs and outputs, and GLES2.0 does not support that. 

I did not know about uniform buffers actually, but looks like they are not supported in GLES2.0 (correct me if I am wrong). If this is really the case, then Diligent can't support GLES2.0. 

Diligent is designed as a modern cross-platform library targeting next-gen APIs. It has to sacrifice backwards compatibility with really old APIs

**Comment by eugeneko** [comment]
> I did not know about uniform buffers actually, but looks like they are not supported in GLES2.0 (correct me if I am wrong).

Yeah, you are right. It was the first thing I've checked when looked at this issue, and Diligent looks really tied to these guys.

> It has to sacrifice backwards compatibility with really old APIs

For mobiles GLES 2.0 is not that old.
I think it would disappear in ~5 years tho, so indeed this issue isn't that severe...

It's good thing you stick to modern interface. Maintaining all this old stuff and managing uniforms would have had awful impact on usability.

**Comment by DiligentGraphics** [comment]
GLES2.0 can't be supported by Diligent Engine because this old API lacks crucial abstractions (uniform buffers and other).
