### ISSUE TITLE
Remove the "Which backend to use" popup

### ISSUE THREAD

**Issue by bharatr1993** [DiligentGraphics/DiligentEngine#162]
I am trying to build a game, everything is set up and is working.

Is it possible to force it to use directx12 or vulkan to render instead of explicitly asking through a popup window???

**Comment by TheMostDiligent** [comment]
You can use `-mode d3d12` command line option to select d3d12 backend.
https://github.com/DiligentGraphics/DiligentSamples#build-and-run-instructions
