### ISSUE TITLE
3 Errors When Builiding in Code::Blocks

### ISSUE THREAD

**Issue by Xiji5** [DiligentGraphics/DiligentEngine#166]
I recently found this project and I was interested in using the library. I downloaded the release version of the library (specifically version 2.5.1, keep in mind, by stating I downloaded the release version, I mean I didn't download the library from using "git clone", rather I just downloaded the library here at https://github.com/DiligentGraphics/DiligentEngine/releases/tag/v2.5.1) Once downloaded, I used cmake GUI version 3.22.0 to build the cmake files. I have my source code for the Diligent Engine, I have downloaded in a folder on my desktop, I also have where the binaries will be in a path like "C:/DiligentEngine".  I then clicked "Generate", and selected the generator for the project as, "Codeblocks - MinGW Makefiles". I selected finish, and it generated smoothly into C:/DiligentEngine. I then opened the codeblocks project that was formed after it was generated from cmake. Once opened in codeblocks, I selected the "Build and Run" option. After 45 minutes-1 hour, I get the errors:

Line 74 DiligentCore-ValidateFormatting] Error 9009
Line 2158 DiligentCore/CMakeFiles/DiligentCore-ValidateFormatting.dir/allj Error 2
Line 135 allj Error 2

Build failed: 3 error(s)

Any help would be great.

Diligent Engine Version: 2.5.1
Cmake Version: 3.22.0
Codeblocks Version: "Codeblocks-20.03 MinGW"

PC specs:
Operating System: Windows 10 Professional 64 bit
Processor: AMD A4-3420 APU with Radeon(tm) HD Graphics 2.80 GHz
RAM: 4.00 GB
System Type: 64-bit operating system, x86-based processor

**Comment by TheMostDiligent** [comment]
Why are you using MinGW to build on Windows? It should work, but is such a pain. Also, Direct3D11 and Direct3D12 are not enabled in MinGW. [The recommended way](https://github.com/DiligentGraphics/DiligentEngine#win32) is to use Visual Studio build.
Try to use `-DDILIGENT_NO_FORMAT_VALIDATION=ON` with CMake.

**Comment by Xiji5** [comment]
Okay, I'll try it, thanks for the answer!

Also I love this library so far (even if I haven't used it yet) :)

**Comment by Xiji5** [comment]
Okay, I did what you said, and I got a lot of GLFW errors.

**Comment by TheMostDiligent** [comment]
Did you follow the build instructions? FYI, here is [the last build from CI](https://github.com/DiligentGraphics/DiligentEngine/actions/runs/1404311578) - all 6 windows configurations are green, so there is something with your set up.
What errors do you get?

**Comment by Xiji5** [comment]
The errors seem to be coming from GLFWDemo.cpp

Line 116 Error macor "CreateWindowW" requires 11 arguements, but only 4 given

Line 469 Error macor "CreateWindowW" requires 11 arguements, but only 4 given

Line 116 error: 'bool Diligent::GLFWDemo::CreateWindowW' is not a status member of 'class ...

And like 50 more errors of just the same thing, about GLFW

**Comment by Xiji5** [comment]
I'll probably just use visual studio instead of codeblocks.
It's not a complete solution to this, but it's a solution.
Anyway thanks for the help. I can't wait to use this library! :)
