### ISSUE TITLE
unused variable causes build to fail in Visual Studio 2022, Windows 11. warning is treated as error

### ISSUE THREAD

**Issue by wegesdal** [DiligentGraphics/DiligentEngine#177]
line 192 in Diligent-Archiver-static     
//const bool         HasSpaces = RootSig.GetTotalSpaces() > 1;

Build succeeds if this line is commented out.

**Comment by TheMostDiligent** [comment]
This has been fixed in the core module, but the commit has yet been updated in the main module.

**Comment by TheMostDiligent** [comment]
The main module has been updated so the issue should be fixed now.
