### ISSUE TITLE
Vulkan for others platform like linux ?

### ISSUE THREAD

**Issue by Hideman85** [DiligentGraphics/DiligentEngine#18]
I'm interested by your engine and really like run it over Vulkan backend on linux and on all platform.

**Comment by DiligentGraphics** [comment]
Vulkan ports to Linux, Android and iOS/MacOS are all planned.

**Comment by Hideman85** [comment]
I have another question, is it normal on all your tutorials samples where we can find «Workers threads» I cannot change this value ? I using linux.

**Comment by DiligentGraphics** [comment]
Yes, because Diligent supports multithreading for Direct3D11, Direct3D12, and Vulkan backends, but not for OpenGL.

**Comment by Hideman85** [comment]
Ha okey, thanks so much for your replies.

**Comment by DiligentGraphics** [comment]
NP. Feel free to reopen this issue/create new one if you have more questions.
