### ISSUE TITLE
Same code that runs on Vulkan, doesn't run on D3D12.

### ISSUE THREAD

**Issue by DaOnlyOwner** [DiligentGraphics/DiligentEngine#186]
Hello Mr. Diligent, 
my application runs on Vulkan Backend, but not on the D3D12 backend. I haven't tested other backends because I use raytracing...
It apparently cannot create a pipeline state...

- OS: Windows 10
- Visual Studio 2022 Debug x64 + Cmake 
- RTX 2080 + Treiber 511.79
- DEBUG OUTPUT: 
Diligent Engine: Info: User-defined allocator is not provided. Using default allocator.
Diligent Engine: Info: D3D12-capable adapter found: NVIDIA GeForce RTX 2080 (8010 MB)
Diligent Engine: Info: User-defined allocator is not provided. Using default allocator.
Diligent Engine: Info: Created dynamic memory page. Size: 1.00 MB; GPU virtual address 0x82d1000
Diligent Engine: Info: Can not disable SeparablePrograms
Diligent Engine: Info: Max device shader model: 6_5
Diligent Engine: Info: Loaded DX Shader Compiler, version 1.5
Diligent Engine: ERROR in Diligent::PipelineStateD3D12Impl::PipelineStateD3D12Impl() (PipelineStateD3D12Impl.cpp, 771): Failed to create pipeline state
Diligent Engine: ERROR in Diligent::RenderDeviceBase<struct Diligent::EngineD3D12ImplTraits>::CreateDeviceObject() (RenderDeviceBase.hpp, 511): Failed to create Pipeline State object 'Composite PSO'

Respective Code:
`    ci.PSODesc.Name = "Composite PSO";
    ci.PSODesc.PipelineType = PIPELINE_TYPE_GRAPHICS;
    ci.PSODesc.ResourceLayout.DefaultVariableType = SHADER_RESOURCE_VARIABLE_TYPE_MUTABLE;
    ci.GraphicsPipeline.PrimitiveTopology = PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
    ci.GraphicsPipeline.NumRenderTargets = 1;
    ci.GraphicsPipeline.RTVFormats[0] = Renderer::Inst().GetSwapchain()->GetDesc().ColorBufferFormat;
    ci.GraphicsPipeline.DepthStencilDesc.DepthEnable = false;
    ci.GraphicsPipeline.DepthStencilDesc.DepthWriteEnable = false;
    ci.GraphicsPipeline.RasterizerDesc.CullMode = CULL_MODE_NONE;`

This is my function for creating a vertex shader:
`ShaderCreateInfo sci;
    sci.SourceLanguage = SHADER_SOURCE_LANGUAGE_HLSL;
    sci.UseCombinedTextureSamplers = true;
    sci.ShaderCompiler = SHADER_COMPILER_DXC;

    sci.pShaderSourceStreamFactory = Renderer::Inst().GetShaderStreamFactory();
    {
        sci.Desc.ShaderType = SHADER_TYPE_VERTEX;
        sci.EntryPoint = "main";
        sci.Desc.Name = name;
        sci.FilePath = filename;
        Renderer::Inst().GetDevice()->CreateShader(sci, &vs);
        if (vs == nullptr)
        {
            BLE_ERROR("Couldn't create shader {}", filename);
        }
    }
    ci.pVS = vs;
    return *this;`

Pixel shader code looks the same.
Fails at CreateGraphicsPipelineState().
I attempt to shade a gbuffer with this pass. In Vulkan, everything works fine, but not in DirectX 12. 

Cheers and thanks
DaOnlyOwner

**Comment by TheMostDiligent** [comment]
It is hard to provide any suggestion based on the information you provided - it is very generic and does not have any specific details.
In Direct3D12, if you run in Debug mode, the debug layers will print detailed information about why your pipeline failed to create.
Did you run it in debug mode?

**Comment by DaOnlyOwner** [comment]
Yeah, the output I provided is in Debug mode, and no debug message is printed even though I activated validation. 
This is how I initialize the backend:
```
case InitInfo::RenderBackend::D3D12:
	{
		auto getD3 = LoadGraphicsEngineD3D12();
		EngineD3D12CreateInfo D3Ci;
		D3Ci.EnableValidation = true;// info.enableDebugLayers;
		D3Ci.Features.RayTracing = DEVICE_FEATURE_STATE_ENABLED;
		D3Ci.SetValidationLevel(VALIDATION_LEVEL_2);
		auto* d3Factory = getD3();
		d3Factory->CreateDeviceAndContextsD3D12(D3Ci, &device, &imm);
		d3Factory->CreateSwapChainD3D12(device.RawPtr(), imm.RawPtr(), sdesc, FullScreenModeDesc{}, diligentWindow, &swapChain);
		d3Factory->CreateDefaultShaderSourceStreamFactory(nullptr, &streamFactory);
	}

If it helps, my code is here: https://github.com/DaOnlyOwner/BlueLeavesEngine

Thanks again.

**Comment by TheMostDiligent** [comment]
I suggest you try to load your pipeline in one of the tutorials

**Comment by DaOnlyOwner** [comment]
Okay the pipeline cannot be created in the tutorial, it fails there too.

**Comment by TheMostDiligent** [comment]
All Shader compiler errors are in the output

**Comment by DaOnlyOwner** [comment]
I now use the vertex shader from the sample code (screen space triangle) and it works now. Still don't know why no error was reported. Anyways, thanks for the help.
