### ISSUE TITLE
Does not compile. Fresh clone

### ISSUE THREAD

**Issue by RealAstolfo** [DiligentGraphics/DiligentEngine#187]
- OS Gentoo Linux
- Build tools Clang 13.0.1 CMake 3.22.3
it defaults to "-Werror" ? and i have no idea how to remove "-Werror" which is causing the build fails. it also seems that -DDILIGENT_NO_FORMAT_VALIDATION=OFF does not actually stop it, since after manually fixing the "errors" by simply removing them from the build, it still tries to run clang-format

`
cmake -S . -B ./build/Linux64 -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang

Target Platform: Linux
D3D11_SUPPORTED:  FALSE
D3D12_SUPPORTED:  FALSE
GL_SUPPORTED:     TRUE
GLES_SUPPORTED:   FALSE
VULKAN_SUPPORTED: TRUE
METAL_SUPPORTED:  FALSE

-- The C compiler identification is Clang 13.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/llvm/13/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.9.10", minimum required is "3")
-- optimizer enabled
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- SPIRV-Cross: Finding Git version for SPIRV-Cross.
-- Found Git: /usr/bin/git (found version "2.35.1")
-- SPIRV-Cross: Git hash: 2aec9853
-- xxHash build type: Release
Requirement already satisfied: libclang in /home/dots/.local/lib/python3.9/site-packages (13.0.0)
Requirement already satisfied: jinja2 in /usr/lib/python3.9/site-packages (3.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/lib/python3.9/site-packages (from jinja2) (2.1.0)
-- Including X11 support
-- Found X11: /usr/include
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dots/Documents/DiligentEngine/build/Linux64

cmake --build ./build/Linux64

Irrelevant Build Stuffs...

/home/dots/Documents/DiligentEngine/DiligentCore/Graphics/GraphicsEngineVulkan/src/BottomLevelASVkImpl.cpp:59:20: error: variable 'MaxPrimitiveCount' set but not used [-Werror,-Wunused-but-set-variable]
            Uint32 MaxPrimitiveCount = 0;
                   ^
/home/dots/Documents/DiligentEngine/DiligentCore/Graphics/GraphicsEngineVulkan/src/BottomLevelASVkImpl.cpp:102:20: error: variable 'MaxBoxCount' set but not used [-Werror,-Wunused-but-set-variable]
            Uint32 MaxBoxCount = 0;
                   ^
2 errors generated.
gmake[2]: *** [DiligentCore/Graphics/GraphicsEngineVulkan/CMakeFiles/Diligent-GraphicsEngineVk-static.dir/build.make:104: DiligentCore/Graphics/GraphicsEngineVulkan/CMakeFiles/Diligent-GraphicsEngineVk-static.dir/src/BottomLevelASVkImpl.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:3522: DiligentCore/Graphics/GraphicsEngineVulkan/CMakeFiles/Diligent-GraphicsEngineVk-static.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

`

**Comment by TheMostDiligent** [comment]
We will take a look. Apparently new version of clang is more strict about warnings -  we currently use clang 10 on CI.
Can you use clang 10 for now until we fix it?

**Comment by RealAstolfo** [comment]
Ill definitely try. gcc worked out of the box surprisingly despite the warning /shrug

**Comment by TheMostDiligent** [comment]
> Ill definitely try. gcc worked out of the box surprisingly despite the warning /shrug

CMake downgrades optimization level to `O1` for release configurations to make it work.

There seems to be no official package for clang-13. Can you provide instructions how you installed it?

**Comment by RealAstolfo** [comment]
the availability of updated clang is depending on the linux distribution you use. Gentoo already has marked llvm-13 to llvm-11 stable, llvm-10 had been removed from age

**Comment by TheMostDiligent** [comment]
We use Ubuntu and there is no official clang-13 package yet.

`DEFAULT_INITIALIZER(SomeValue)` works if you use the header.

**Comment by RealAstolfo** [comment]
> We use Ubuntu and there is no official clang-13 package yet.
> 
> `DEFAULT_INITIALIZER(SomeValue)` works if you use the header.

unless you are using C, lol
notice that the macro doesnt actually perform anything
`
#if DILIGENT_C_INTERFACE

#    define DILIGENT_BEGIN_NAMESPACE(Name)
#    define DILIGENT_END_NAMESPACE

#    define DILIGENT_TYPED_ENUM(EnumName, EnumType) \
        typedef EnumType EnumName;                  \
        enum _##EnumName

#    define DILIGENT_DERIVE(TypeName) \
        {                             \
            struct TypeName _##TypeName;

#    define DEFAULT_INITIALIZER(x)

#    define DILIGENT_GLOBAL_FUNCTION(FuncName) Diligent_##FuncName

#    define DILIGENT_BEGIN_INTERFACE(Iface, Base) \
        typedef struct Iface                      \
        {                                         \
            struct Iface##Vtbl* pVtbl;            \
        } Iface;                                  \
        struct Iface##Methods

#    define DEFAULT_VALUE(x)

#    define CALL_IFACE_METHOD(Iface, Method, This, ...) (This)->pVtbl->Iface.Method((I##Iface*)(This), ##__VA_ARGS__)

// Two levels of indirection are required to concatenate expanded macros
#    define DILIGENT_CONCATENATE0(X, Y) X##Y
#    define DILIGENT_CONCATENATE(X, Y)  DILIGENT_CONCATENATE0(X, Y)

#else

#    define DILIGENT_BEGIN_NAMESPACE(Name) \
        namespace Name                     \
        {

#    define DILIGENT_END_NAMESPACE }

#    define DILIGENT_TYPED_ENUM(EnumName, EnumType) enum EnumName : EnumType

#    define DILIGENT_DERIVE(TypeName) : public TypeName \
        {

#    define DEFAULT_INITIALIZER(x) = x

#    define DILIGENT_GLOBAL_FUNCTION(FuncName) FuncName

#    define DILIGENT_BEGIN_INTERFACE(Name, Base) struct Name : public Base

#    define DEFAULT_VALUE(x) = x

#endif
`

**Comment by TheMostDiligent** [comment]
Yes, this is because in C language there are no default member initializes.

**Comment by RealAstolfo** [comment]
> Yes, this is because in C language there are no default member initializes.

Right, which kind of leaded to the next problem, is there an alternative already made for the C interface? i just kinda assumed it came all it needed for C

**Comment by TheMostDiligent** [comment]
I suppose you can use `memset()` or a similar function to zero-initialize the memory. This is a C language question that is not related to Diligent API.

**Comment by RealAstolfo** [comment]
i did initially do that, then quickly found that if i dont manually enter all the values, it simply wont run correctly. even with the easy fixes like setting the engineAPIversion number so it can launch the instance. thanks for the input though.

**Comment by TheMostDiligent** [comment]
There is C++ language that provides all that for you. If you don't/can't use c++ for some reason, you will have to manually initialize the structs in C, there is no other way.
