### ISSUE TITLE
Minimal example of CMake setup

### ISSUE THREAD

**Issue by Liareth** [DiligentGraphics/DiligentEngine#19]
It would be nice if there was a minimal example about how to link this to an existing CMake project. I'm struggling to figure out how to link this however, because the existing instructions are based around how to generate the project on its own and build it with the samples, rather than how to link the core only into an existing project.

For example, if I could do `add_subdirectory(external/diligentcore)` (cloned from your repo) and then `target_link_libraries(existing_project DiligentCore)` and everything just worked properly, I would be very happy.

**Comment by NicolasRicard** [comment]
I agree, I'd like to have the minimal example for CMake project too.

**Comment by DiligentGraphics** [comment]
Please take a look at [Integration with Diligent Engine] (https://github.com/DiligentGraphics/DiligentEngine/blob/master/README.md#integration-with-diligent-engine) section
