### ISSUE TITLE
not possible to build nativelly with mingw

### ISSUE THREAD

**Issue by AndreyMlashkin** [DiligentGraphics/DiligentEngine#192]
To reproduce the problem call:
cmake -S . -B ./build/MinGW -D CMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
 cmake --build .\build\MinGW\ -j6

Error:
internal error in mingw32_gt_pch_use_address, at config/i386/host-mingw32.c:192: MapViewOfFileEx: Attempt to access invalid address.

It can be fixed the same way as it is fixed here:
https://github.com/conan-io/conan-center-index/pull/10163

**Comment by AndreyMlashkin** [comment]
Please, also check compiled libraries names for MinGW.
I've got
libGraphicsEngineOpenGL_64r.dll.a and
libGraphicsEngineVk_64r.dll.a

**Comment by TheMostDiligent** [comment]
Diligent provides extensive means for [custom build configuration](https://github.com/DiligentGraphics/DiligentEngine#customizing-build).
To enable RTTI, [custom_configure_build](https://github.com/DiligentGraphics/DiligentEngine#customizing-build) function should work: it is called after Diligent finishes configuring each target, and RTTI can be enabled if necessary.
The function can be defined in the same CMake file before including the Diligent source dir.

**Comment by TheMostDiligent** [comment]
> libGraphicsEngineOpenGL_64r.dll.a and
> libGraphicsEngineVk_64r.dll.a

These are likely export libraries. The dll's should be in the `bin` folder.

**Comment by AndreyMlashkin** [comment]
Thank you for a prompt answer and a very quick fix! It works for me

**Comment by TheMostDiligent** [comment]
[MinGW configuration](https://github.com/DiligentGraphics/DiligentEngine/runs/6361468836?check_suite_focus=true) has been added to CI.
