### ISSUE TITLE
Disable Warning as Error

### ISSUE THREAD

**Issue by LDprg** [DiligentGraphics/DiligentEngine#195]
How can I disable Warning as Error in the libary. 
When I am linking it via cmake into my project my project also enables it.
How can I disable the flag?

Error:
error C2220: Die folgende Warnung wird als Fehler behandelt.

**Comment by TheMostDiligent** [comment]
Can you provide the information about your build set up as the issue template was asking?

**Comment by LDprg** [comment]
Oh, Sorry. I am on WIndows using Visual Studio 2017 as IDE. My Build setup ist very easy just this repository as submodule linked into my project. I am using cmake for this, just as described in the Readme in the "Integrating Diligent Engine with Existing Build System" and "Your Project Uses Cmake" section.
The setup works perfectly fine, but Diligent Engine enables Warning as Error in my project. If I disable the flag in Visual Studio the code compiles and everything works. However as soon as I regenerate my project with cmake it stops working again. Therefore I would like to disable the flag in cmake somehow.

**Comment by TheMostDiligent** [comment]
Which Diligent targets to you link your project with in your CMake? Warning as error is set by `Diligent-BuildSettings`, which is a private dependency, so the settings should leak to external projects.

**Comment by LDprg** [comment]
Well I just linked this repository into cmake and linked following stuff:

target_link_libraries(proj
PRIVATE Diligent-GraphicsEngineD3D11-shared
PRIVATE Diligent-GraphicsEngineOpenGL-shared
PRIVATE Diligent-GraphicsEngineD3D12-shared
PRIVATE Diligent-GraphicsEngineVk-shared
PRIVATE Diligent-Imgui)

So you say that `Diligent-BuildSettings` causes Warning as error? Is there a way for disableling it?

**Comment by TheMostDiligent** [comment]
I can't reproduce it. There is [Tutorial00](https://github.com/DiligentGraphics/DiligentSamples/blob/master/Tutorials/Tutorial00_HelloWin32/CMakeLists.txt) that explicitly [links with Diligent-BuildSettings](https://github.com/DiligentGraphics/DiligentSamples/blob/master/Tutorials/Tutorial00_HelloWin32/CMakeLists.txt#L19) and thus have the /WX option. However, if I remove this line, the option is unset.

Do you want to disable the option for your project only (the `proj`) or globally for all projects in the solution?

**Comment by LDprg** [comment]
For me it is only important that `proj` has the option disabled. 
I played around with the link statements.
I found that the `target_link_libraries(Engine Diligent-Imgui)` causes the option to be enabled

**Comment by TheMostDiligent** [comment]
I don't understand, I can't reproduce it. There was similar issue reported before and we made sure that internal settings to not leak out.
Can you try to use the following CMake file with [Tutoiral00](https://github.com/DiligentGraphics/DiligentSamples/blob/master/Tutorials/Tutorial00_HelloWin32/CMakeLists.txt):

```CMake
cmake_minimum_required (VERSION 3.6)

project(Tutorial00_HelloWin32 CXX)

set(SOURCE
    src/Tutorial00_HelloWin32.cpp
)

add_executable(Tutorial00_HelloWin32 WIN32 ${SOURCE})
target_include_directories(Tutorial00_HelloWin32 PRIVATE "../../../DiligentCore")

target_compile_definitions(Tutorial00_HelloWin32 PRIVATE UNICODE)

set_target_properties(Tutorial00_HelloWin32 PROPERTIES
    FOLDER DiligentSamples/Tutorials
)

target_compile_definitions(Tutorial00_HelloWin32 PRIVATE ENGINE_DLL=1)
#target_link_libraries(Tutorial00_HelloWin32 PRIVATE Diligent-BuildSettings)

if(D3D11_SUPPORTED)
    target_link_libraries(Tutorial00_HelloWin32 PRIVATE Diligent-GraphicsEngineD3D11-shared)
endif()
if(D3D12_SUPPORTED)
    target_link_libraries(Tutorial00_HelloWin32 PRIVATE Diligent-GraphicsEngineD3D12-shared)
endif()
if(GL_SUPPORTED)
    target_link_libraries(Tutorial00_HelloWin32 PRIVATE Diligent-GraphicsEngineOpenGL-shared)
endif()
if(VULKAN_SUPPORTED)
    target_link_libraries(Tutorial00_HelloWin32 PRIVATE Diligent-GraphicsEngineVk-shared)
endif()
target_link_libraries(Tutorial00_HelloWin32 PRIVATE Diligent-Imgui)

copy_required_dlls(Tutorial00_HelloWin32)
```

As long as it is not linked with `Diligent-BuildSettings`, there is no `/WX` in the settings.

**Comment by LDprg** [comment]
I wasn't able to fix It by chaning my code accordently. As soon as I link `Diligent-Imgui` into the project Waning as Error is enabled. It seems like the other code doesn't matter at all.
My way to deal with it is now to disabe the warning with a `#pragma`. In general I like Warning as Error because it's forces me to write better and cleaner code.

**Comment by TheMostDiligent** [comment]
So you after you used the [CMake](https://github.com/DiligentGraphics/DiligentEngine/issues/195#issuecomment-1120758078) I shared in Tutorial00_HelloWin32, you got the `/WX` in the project's settings?

> As soon as I link Diligent-Imgui into the project Waning as Error is enabled.

`Diligent-Imgui` does not have a single public dependency. This is starting to look strange. Which CMake version are you using? Also, can you try to use Visual Studio 2019?

**Comment by TheMostDiligent** [comment]
I don't know what else to suggest. The CMake I sent you links `Tutorial00_HelloWin32` with `Diligent-Imgui`, but  `/WX` option (as well as all other options) does not leak out.
I don't know what in your setup makes it work differently.
You can try to use
```CMake
target_compile_options(proj PRIVATE /WX-)
```
as a workaround.

**Comment by LDprg** [comment]
I found the problem! I was using cmake 3.23.0-rc2 and to check if a newer cmake version would cause the problem I updated to cmake 3.23.1. With the new version the problem has gone! Seems like a cmake bug in an (not very old) version.
Now everything behaves as expected.
Thanks for your help!

**Comment by TheMostDiligent** [comment]
OK, CMake bug definitely explains it.
Note that release candidates (rc) are called this for a reason. I personally never use pre-release versions.
