### ISSUE TITLE
AtmosphereSample release mode can't run.

### ISSUE THREAD

**Issue by chaosfire** [DiligentGraphics/DiligentEngine#2]
AtmosphereSample 
x64 Debug is OK. but Release mode failed to run.

**Comment by DiligentGraphics** [comment]
Is this on Windows? I just tried to clone and build the fresh copy, it seems to be working fine on both Win32 & Universal Windows.

**Comment by DiligentGraphics** [comment]
Closing this issue as I tested the sample in Release v2.2 and it seems to work fine on Win32, Linux and UWP platforms. Please reopen if you still see the problem.
