### ISSUE TITLE
Namespace the various CMake projects

### ISSUE THREAD

**Issue by Liareth** [DiligentGraphics/DiligentEngine#20]
I recommend renaming the various CMake targets in a more namespaced way - e.g. DiligentCommon rather than Common or DiligentGraphicsEngine rather than GraphicsEngine. The current targets have very generic names which are likely to clash with existing targets.

**Comment by madwax** [comment]
I have to agree.  I've been looking to intergrate Diligent into a much bigger moden CMake base project and while it would not clash with anything it would make navigating in the IDE's cleaner.   Very cosmetic it know

**Comment by DiligentGraphics** [comment]
@madwax 
Does your IDE support folders? To simplify project navigation, this will be more useful because there are some third-party projects too.
