### ISSUE TITLE
cmake problems when generating visual studio project

### ISSUE THREAD

**Issue by delphifirst** [DiligentGraphics/DiligentEngine#200]
- Windows11 21H2
- Visual Studio 2019 Debug x64 + CMake 3.16.4

When I clicked "Configure" to generate visual studio project, I got the following error:
```
CMake Error at DiligentCore/BuildUtils.cmake:314 (add_custom_command):
  add_custom_command called with OUTPUT containing a "<".  This character is
  not allowed.
Call Stack (most recent call first):
  DiligentCore/CMakeLists.txt:464 (install_combined_static_lib)
```

I searched and found that it seems we should change `$<CONFIG>` to `$<CMAKE_CFG_INTDIR>`. (https://cmake.org/pipermail/cmake/2014-August/058375.html). I tried and this works for me.

I'm not sure whether this is the correct solution, so I create this issue.

**Comment by TheMostDiligent** [comment]
The correct solution is to update CMake to the latest version

**Comment by delphifirst** [comment]
OK. Maybe the build guide should be updated. It says cmake 3.16 or later is required, so I just use cmake 3.16.
