### ISSUE TITLE
Texture Loader dumps red and blue channels

### ISSUE THREAD

**Issue by RobertMtx** [DiligentGraphics/DiligentEngine#218]
A lot of my textures are being loaded with the green and blue channels zeroed out, while using the texture loader. I confirmed this happens with a sample by swapping out the DGLogo.png texture with one of the PNG images for Tutorial 03 (texturing), and get the same red result. I attached one of these textures for testing. I have many more, if needed. I've confirmed this happens with at least PNG and JPG formats, but not sure about others.

I'm pretty certain this will happen on all system types. But if it doesn't, let me know, and I will give you details about mine, along with screen shots and anything else needed.

Test Texture:
[DGLogo.zip](https://github.com/DiligentGraphics/DiligentEngine/files/10053703/DGLogo.zip)

Edit: I haven't confirmed this, but its possible this may be happening with greyscale textures. It would make sense that if there is only one channel available, you would put it in red! :)

**Comment by TheMostDiligent** [comment]
This is a single-channel PNG image that Diligent loads a single-channel `R8_UNORM` texture. If you want to load it as RGBA texture, you should explicitly specify the format and Diligent will convert it to 4-channel texture:

```cpp
TextureLoadInfo loadInfo;
loadInfo.IsSRGB = true;
loadInfo.Format = TEX_FORMAT_RGBA8_UNORM;
RefCntAutoPtr<ITexture> Tex;
CreateTextureFromFile("DGLogo.png", loadInfo, m_pDevice, &Tex);
```

**Comment by RobertMtx** [comment]
Sorry, I didn't realize this was the intended behavior. 

I would recommend making G -> GGG1 the default behavior when loading greyscale formats into full color textures, if that's possible. I doubt most people will want or expect a single red channel texture when loading greyscale. Would there be any way to specify this behavior without knowing what format the texture on disk is in?
