### ISSUE TITLE
OS specific, window creation

### ISSUE THREAD

**Issue by llagardeOSE** [DiligentGraphics/DiligentEngine#222]
We will use a DiligentEngine installation as a third-party.
I mean our code uses only the result of "make install".
This way I do not see how to initialize the windowing system (creating a window) without writing some X11/Win32 code.
I am looking for a way to do:
```
GraphicsTraits traits = ...
traits.width  = 800;
traits.height = 600;
NativeWindow window = WindowingInterface->CreateWindow(traits);
```

In order to feed the engine factory with the created window:
```
IEngineFactoryVk *engineFactory = ...
engineFactory->CreateSwapChainVk(_pDevice, _pImmediateContext, SCDesc, window, &_pSwapChain);
```

**Comment by llagardeOSE** [comment]
I guess I will use SDL or GLFW as another third-party.

**Comment by TheMostDiligent** [comment]
Yes, native application framework is currently not installed. It is expected that the app will include this project in its build system.
