### ISSUE TITLE
List minimum API versions in README.md

### ISSUE THREAD

**Issue by eugeneko** [DiligentGraphics/DiligentEngine#223]
It would be great if you list which API versions Diligent can actually use as backend.

For example, I _assume_ that Diligent needs OpenGL ES 3.0 (or is it 3.1?) on mobiles, but I don't see any obvious confirmation for this.
Same question for Web. Is it WebGL 2?
Same question for Windows. Is it DX11.0 or DX11.1? I think it is 11.1, looking at `ID3D11DeviceContext1`...
Same question for Vulkan. 1.0 or later?

This is all very important information (at least for me), so I believe it should be somewhere on the main page.

**Comment by TheMostDiligent** [comment]
It is OpenGL ES 3.0 / OpenGL4.1 / WebGL2 / Direct3D11.1 (feature level 10.0, maybe even 9 will work) / Vulkan1.0

Will add this to the readme.
