### ISSUE TITLE
render target failed

### ISSUE THREAD

**Issue by zhaokaixs** [DiligentGraphics/DiligentEngine#224]
i have two texture
eg.
              
`	       
		RefCntAutoPtr<ITexture>		 m_rendertarget1
		RefCntAutoPtr<ITexture>		 m_rendertarget2;

                TextureDesc	desc;
		desc.Width = width;
		desc.Height = height;
		desc.Name = "Backbuffer Texture";
		desc.Format = m_format;
		desc.Usage = USAGE_DEFAULT;
		desc.CPUAccessFlags = CPU_ACCESS_NONE;
		desc.Type = RESOURCE_DIM_TEX_2D;
		desc.BindFlags = BIND_SHADER_RESOURCE | BIND_RENDER_TARGET;
                CreateTexture(desc, nullptr, &m_rendertarget1);
                CreateTexture(desc, nullptr, &m_rendertarget2);
`
when i draw a image to m_rendertarget1 ,  and save m_rendertarget1 to image file,it's successs,
but  draw m_rendertarget1  to m_rendertarget2, save to image file. the image file is empty .
why not render failed ?

**Comment by zhaokaixs** [comment]
[Tutorial03_Texturing.zip](https://github.com/DiligentGraphics/DiligentEngine/files/10317607/Tutorial03_Texturing.zip)

**Comment by TheMostDiligent** [comment]
In your snippet, you use SRV of `m_RenderTexture`, but you never use SRV of `m_RenderTexture1`. This might be the reason.

**Comment by zhaokaixs** [comment]
> 



> In your snippet, you use SRV of `m_RenderTexture`, but you never use SRV of `m_RenderTexture1`. This might be the reason.
[Tutorial03_Texturing.zip](https://github.com/DiligentGraphics/DiligentEngine/files/10317607/Tutorial03_Texturing.zip) is my test code,
