### ISSUE TITLE
Any plans to support metal?

### ISSUE THREAD

**Issue by DaOnlyOwner** [DiligentGraphics/DiligentEngine#23]
Hey ;)
Are there any plans to support Metal? The problem is obviously that apple doesn't update OpenGL drivers anymore and not being able to use compute shaders is a huge restriction.

**Comment by DiligentGraphics** [comment]
Yes, there are plans to support Metal. 
Enabling Vulkan backend on mac/iOS via MoltenVk is the first planned step (https://github.com/DiligentGraphics/DiligentCore/issues/34). This should unlock almost all functionality.
Supporting Metal natively is the second step.

**Comment by DiligentGraphics** [comment]
SPIRV-Cross is able to convert SPIRV to metal shading language

**Comment by DiligentGraphics** [comment]
Diligent Engine now supports Vulkan on MacOS (that runs via MoltenVK).

**Comment by dolphineye** [comment]
Hi :) Any ETA about a Metal support for iOS?

**Comment by DiligentGraphics** [comment]
Enabling Metal through MoltenVK is a matter of resolving few build issues.
Implementing native Metal backend is not in the immediate plans and hopefully someone will help with this https://github.com/DiligentGraphics/DiligentCore/issues/49.

**Comment by dolphineye** [comment]
Alright. Thanks for the quick answer :)

**Comment by DiligentGraphics** [comment]
@DaOnlyOwner, @dolphineye  Metal is now supported on iOS via MoltenVK. According to [this doc](https://github.com/KhronosGroup/MoltenVK/blob/master/Docs/MoltenVK_Runtime_UserGuide.md#limitations), MoltenVK has very few limitations, and compute shaders are definitely supported.
Like on other platforms, the engine uses HLSL shaders that are converted to MSL by MotlenVK under the hood. Closing this issue for now.
