### ISSUE TITLE
General Question about and SDL game

### ISSUE THREAD

**Issue by lonnietc** [DiligentGraphics/DiligentEngine#230]
Hello,

Hope that you are doing well today.

There is a bit dated SDL2 game (Tesseract 3D Engine, from Cube2) that I am interested in trying to update to a modern rendering engine so that I can also learn in the process about this area as well, but it seems to use SDL2 and OpenGL for the rendering part.

It seemed to make sense to me to consider a modern rendering engine that could also do Vulkan but from a good framework that covered more.

This will initially be run on Windows, but can also have builds for Linux and MacOS as well.

Do you think that Diligent Engine is capable and good for this purpose?

Thanks and have a great day

**Comment by TheMostDiligent** [comment]
Diligent sounds like a good fit for your needs. It supports Windows, Linux, Mac platforms, D3D12, Vulkan under the hood and uses modern graphics API abstractions

**Comment by lonnietc** [comment]
Hello,

Does Diligent Engine have any Golang bindings?

Thanks

**Comment by TheMostDiligent** [comment]
No

**Comment by lonnietc** [comment]
Thanks and have a great day.
