### ISSUE TITLE
Incorrect index buffer view in D3D12 backend when using dynamic usage buffers

### ISSUE THREAD

**Issue by chelvisgit** [DiligentGraphics/DiligentEngine#236]
With D3D12, mapping and unmapping a vertex & index buffer conveys to a memory overwrite: Checking the Index buffer content with RenderDoc, buffer appears to have some floats instead the valid indexes (uint32) on certain parts. It does not happens with D3D11 backend (same code).

Digging into the Diligent code we have seen that there is a huge memory array allocated to do the mapping cache. 
The problem is that while the returned pointer by the MapBuffer() points to the correct place, using that same buffer with setIndexBuffer() shows in RenderDoc the contents of the dynamic page instead of the section allocated to the index buffer.

Diagram:
![Clipboard - March 23, 2023 8_12 AM](https://user-images.githubusercontent.com/29204210/227186847-799cf7eb-42f0-4f25-8b15-27b830105593.png)

This is at least in theory what I think is going on. Could you provide me with any tips to help investigate the problem further?

System:
Windows 10 Pro 22H2
Visual Studio 2019 Release x64
NVIDIA GTX 1080 Driver 531.14
AMD Ryzen 9 3900X 12 - 3.80GHz

**Comment by TheMostDiligent** [comment]
The contents of the dynamic buffer is valid during a single frame only - it is not preserved between frames. If you run in Debug mode, the engine will print the errors if you try to use a buffer that was not mapped in the frame.

Please take a look at [Tutorial 11](https://github.com/DiligentGraphics/DiligentSamples/tree/master/Tutorials/Tutorial11_ResourceUpdates) - it describes different resource usage/update strategies and tradeoffs.

**Comment by chelvisgit** [comment]
> Dynamic textures is not really a thing. If you need to upload textures a lot, you should likely create staging texture, update it and then copy to USAGE_DEFAULT texture
***buffer** creation with USAGE_DEFAULT I wanted to say
btw, thanks for the texture tip. Probably I'll need it in the future.

**Comment by TheMostDiligent** [comment]
Sounds good.
Feel free to close the issue if it is resolved.
Note that there is also a [discord channel](https://discord.com/invite/t7HGBK7) for discussions.
