### ISSUE TITLE
Can it be used in qt

### ISSUE THREAD

**Issue by zhichangxuexi** [DiligentGraphics/DiligentEngine#239]

**Comment by TheMostDiligent** [comment]
Note that for discussions, it is easier to use the [discord channel](https://discord.com/invite/t7HGBK7)

I don't see any reason why not.

**Comment by zhichangxuexi** [comment]
then how to use it in qt,Is there a tutorial available

**Comment by TheMostDiligent** [comment]
No, there is no tutorial
