### ISSUE TITLE
Is the world coordinate system and model coordinate system of Diligent Engine left-handed or right-handed  coordinate system？

### ISSUE THREAD

**Issue by zhichangxuexi** [DiligentGraphics/DiligentEngine#240]
Is the world coordinate system and model coordinate system of Diligent Engine left-handed or right-handed  coordinate system？

**Comment by TheMostDiligent** [comment]
Note that for discussions, it is easier to use the [discord channel](https://discord.com/invite/t7HGBK7)

Diligent math library uses the right-handed coordinate system by default.

**Comment by zhichangxuexi** [comment]
thanks
