### ISSUE TITLE
I have created a new shader based on your example. How can I obtain the shader code in Opengl？

### ISSUE THREAD

**Issue by zhichangxuexi** [DiligentGraphics/DiligentEngine#241]
I have created a new shader based on your example. How can I obtain the shader code in Opengl？ such as cube.fs or cube.vs these files

**Comment by TheMostDiligent** [comment]
Why do you need shader code in OpenGL - how do you want to use it?
Note that for discussions, it is easier to use the [discord channel](https://discord.com/invite/t7HGBK7)

**Comment by zhichangxuexi** [comment]
I would like to see the converted code in such as cube.fs or cube.vs by Diligent-HLSL2GLSLConverterLib，then analyze if there are any issues

**Comment by TheMostDiligent** [comment]
You can use the [HLSL2GLSLConverter off-line tool](https://github.com/DiligentGraphics/DiligentTools/tree/master/HLSL2GLSLConverter) that uses the same conversion library
