### ISSUE TITLE
which third-party software do you usually use to debug shaders? Can you share some debugging experience? 

### ISSUE THREAD

**Issue by zhichangxuexi** [DiligentGraphics/DiligentEngine#242]
We all know that shader code is not easy to debug. Curiously, could you please ask which third-party software do you usually use to debug shaders code? Can you share some debugging experience? Thank you

**Comment by zhichangxuexi** [comment]
soft such as RenderDoc,Nsight,glDebugger？

**Comment by TheMostDiligent** [comment]
Yes, tools like you mentioned.
Diligent also supports hot shader reloading, which facilitates shader development by a lot.
Take a look at [Tutorial 26](https://github.com/DiligentGraphics/DiligentSamples/tree/master/Tutorials/Tutorial26_StateCache)
