### ISSUE TITLE
I turned Tutorial02_ The two shaders in the Cube tutorial were ported to the GLTFViewer demo, but a compilation error occurred

### ISSUE THREAD

**Issue by zhichangxuexi** [DiligentGraphics/DiligentEngine#244]
I turned Tutorial02_ The two shaders in the Cube tutorial were ported to the GLTFViewer demo, but a compilation error occurred:

![image](https://user-images.githubusercontent.com/40328051/232989772-30c9b040-c1e0-4160-ad4e-fed232e94769.png)
![image](https://user-images.githubusercontent.com/40328051/232990171-b9c80d7a-6a4f-49d8-b23c-72cb224a3acb.png)

1>D:\Source\DiligentEngine_v2.5.3\DiligentSamples\Samples\GLTFViewer\assets\shaders\cube.psh(9,18-28): error X4502: invalid vs_2_0 output semantic 'SV_TARGET'

**I want to render a cube in the GLTFViewer demo**，could you help me

**Comment by TheMostDiligent** [comment]
You don't need Visual Studio to compile the shaders. Add them to the [shader list](https://github.com/DiligentGraphics/DiligentSamples/blob/master/Samples/GLFWDemo/CMakeLists.txt#L16) - CMake will disable shader compilation in VS.

**Comment by zhichangxuexi** [comment]
nice, no problem
