### ISSUE TITLE
I want to add a button event handler, but I found that no matter which button I press, the value here always returns 229

### ISSUE THREAD

**Issue by zhichangxuexi** [DiligentGraphics/DiligentEngine#245]
I want to add a button event handler, but I found that no matter which button I press, the value here always returns 229，like key A,keyW,but key ctrl and key shift are ok
![image](https://user-images.githubusercontent.com/40328051/233235054-e2904f5e-0761-4ba5-ba58-ff6848519c2e.png)

**Comment by TheMostDiligent** [comment]
This is Windows API question, please [consult MSDN](https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-keydown)

Please use [GitHub Discussions](https://github.com/DiligentGraphics/DiligentEngine/discussions) for general questions/discussions.

**Comment by zhichangxuexi** [comment]
![image](https://user-images.githubusercontent.com/40328051/233251710-d2282050-46e4-415b-9441-b2f326f3ef24.png)
I have found the reason, keyboard input should be in English input mode

**Comment by TheMostDiligent** [comment]
Yes, it needs English input
