### ISSUE TITLE
how to use  EnableStencilTest this api

### ISSUE THREAD

**Issue by zhichangxuexi** [DiligentGraphics/DiligentEngine#246]
I want to develop the following effects：
![image](https://user-images.githubusercontent.com/40328051/233249155-7392f305-0778-4142-bf87-be19468e9976.png)
then How can I call the underlying API in the application layer：
void GLContextState::EnableStencilTest(bool bEnable)

**Comment by zhichangxuexi** [comment]
StencilTest function  development for blue contour lines above the picture

**Comment by TheMostDiligent** [comment]
Stencil is controlled through [StencilEnable](https://github.com/DiligentGraphics/DiligentCore/blob/43c5db201eb16554cc93235b81c58bdcb57c097c/Graphics/GraphicsEngine/interface/DepthStencilState.h#L176) member of depth-stencil state.

Please use [GitHub Discussions](https://github.com/DiligentGraphics/DiligentEngine/discussions) for general questions/discussions.
