### ISSUE TITLE
How to Transfer Variables from Vertex Shaders to Pixel Shaders in HLSL, Similar to Opengl's Vary

### ISSUE THREAD

**Issue by zhichangxuexi** [DiligentGraphics/DiligentEngine#247]
![image](https://user-images.githubusercontent.com/40328051/233883075-1f6d16c1-2fcb-45a5-b429-d2230dd27770.png)
![image](https://user-images.githubusercontent.com/40328051/233883107-43752579-d6a8-4f29-bad4-1ce924976150.png)

As shown in the picture, I don't know what to inherit by passing ordinary variables in HLSL. I know you can use varying in Opengl。
![image](https://user-images.githubusercontent.com/40328051/233883601-7ea8b743-1946-4209-b536-a9704751b267.png)

**Comment by TheMostDiligent** [comment]
You add a [semantic](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-semantics) to shader variable, for example:

```hlsl
struct PSInput 
{ 
    float4 Pos : SV_POSITION; 
    float2 UV  : TEX_COORD; 
};
```
