### ISSUE TITLE
Why does the projection matrix appear to be in a left-hand coordinate system

### ISSUE THREAD

**Issue by Haidiye00** [DiligentGraphics/DiligentEngine#252]
![image](https://user-images.githubusercontent.com/132528822/236406021-d18b9be9-c908-42bb-aa97-560e755e6684.png)

![image](https://user-images.githubusercontent.com/132528822/236405970-1680d157-44af-4bc8-afec-3e7db25d7327.png)

Here is how to calculate the projection matrix based on the engine of bgfx
![image](https://user-images.githubusercontent.com/132528822/236406256-d69a7e7f-c0f4-48bd-8e4b-c47e5e9a7425.png)

**Comment by Haidiye00** [comment]
m32 should be -1 but in Diligent it is 1,why,

**Comment by Haidiye00** [comment]
![image](https://user-images.githubusercontent.com/132528822/236408494-6d1f4328-098a-4f07-a842-4c5a5df74693.png)

**Comment by TheMostDiligent** [comment]
Diligent uses DirectX convention by default.

**Comment by TheMostDiligent** [comment]
https://github.com/DiligentGraphics/DiligentCore/blob/master/doc/CoordinateSystem.md

**Comment by Haidiye00** [comment]
thanks
