### ISSUE TITLE
Hello, we want to use DiligentEngine as a part of commercial software, which has just started to develop. Is there anything we should pay attention to

### ISSUE THREAD

**Issue by Haidiye00** [DiligentGraphics/DiligentEngine#254]
Hello, we want to use Diligent Engine as a part of commercial software, which has just started to develop. Is there anything we should pay attention to
![img_v2_9f20a93e-840a-4fa6-aec3-b6577acd760g](https://user-images.githubusercontent.com/132528822/236453565-f17ba86e-040d-4065-804c-7d209287c015.jpg)

**Comment by Alan-FGR** [comment]
If you need Metal support, MoltenVK is working apparently very well for me (limited tests) and rbfx users (a game engine that uses Diligent). However, if you're developing a commercial product, maybe you want to consider supporting Diligent and (as the screenshot suggests) contact them. 

Disclaimer: I'm not associated with Diligent in any way, just think it's fair to financially support stuff you/your business depend on (when possible)

**Comment by TheMostDiligent** [comment]
All code in this repository is distributed under [Apache-2.0 License](https://github.com/DiligentGraphics/DiligentEngine/blob/master/License.txt), which is standard for open-source software. Please read the license and decide if it works for you.
