### ISSUE TITLE
Why do objects display in a left-hand coordinate system

### ISSUE THREAD

**Issue by Haidiye00** [DiligentGraphics/DiligentEngine#255]
![image](https://user-images.githubusercontent.com/132528822/236726687-5040aa14-1a5f-49f3-8722-c7129220762a.png)
look at the picture above,left is rendered in Diligent,and right is rendered in MeshLab,then you can see,The fingers of an object in two picture are reversed

**Comment by TheMostDiligent** [comment]
Because Diligent uses a left-handed coordinate system.

**Comment by Haidiye00** [comment]
![image](https://user-images.githubusercontent.com/132528822/236733402-0f782af0-7f1c-46e9-9058-4d487cdc2f1d.png)
Diligent math library uses the right-handed coordinate system by default.
But rendering  is a left-hand coordinate system， then How do I change the rendering to a right-hand coordinate system

**Comment by TheMostDiligent** [comment]
Please [read this](https://github.com/DiligentGraphics/DiligentCore/blob/master/doc/CoordinateSystem.md) 
If you want right-handed you need to apply a transform that changes handness, for example inverses x axis.

**Comment by Haidiye00** [comment]
The projection matrix in bgfx can support right-hand coordinate systems. Will DiligentEngine support it in the future

**Comment by TheMostDiligent** [comment]
This is the matter of changing the signs of a few members in a matrix.
You can trivially do it yourself if you need it.

**Comment by Haidiye00** [comment]
Can you help provide a demo? Thank you

**Comment by TheMostDiligent** [comment]
You likely need to swap X axis here:
https://github.com/DiligentGraphics/DiligentSamples/blob/7d4f4e14ea21aeb155dcd2d5ca2790c4e429fdb9/Samples/GLTFViewer/src/GLTFViewer.cpp#L121

And also change cull mode here:

https://github.com/DiligentGraphics/DiligentFX/blob/a0a5802d58b63ad158d68fb041f8d6a1b0a3ccdc/GLTF_PBR_Renderer/src/GLTF_PBR_Renderer.cpp#L253
