### ISSUE TITLE
WebGPU support.

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentEngine#257]
It seems webgpu has been deployed in Chrome 113. Maybe consider supporting it somehow in a future version.

**Comment by TheMostDiligent** [comment]
Yes, we are definitely considering this.

**Comment by mingweiLIU** [comment]
Hi, Is there any news about supporting webgpu?

**Comment by TheMostDiligent** [comment]
We performed some initial work. The main problem, not surprisingly, the new shading language they invented.
We are going to get back to this work later this year.

**Comment by mingweiLIU** [comment]
wow, sounds great

**Comment by TheMostDiligent** [comment]
Completed in d3eb78aceda9cb64b9cbae83775f767f40b144d5
