### ISSUE TITLE
gltf 2.0

### ISSUE THREAD

**Issue by 6eye** [DiligentGraphics/DiligentEngine#26]
How to render my blender animation using gltf2.0 as image sequence?

**Comment by DiligentGraphics** [comment]
Please notice that Diligent is a low-level cross-platform graphics API abstraction library. At the moment it does not offer higher-level features such as asset loading or animation. If you want to load gltf2.0 and play animations stored in the file using Diligent, you can use any gltf2.0 loader such as [assimp](https://github.com/assimp/assimp), and implement rendering with Diligent.

**Comment by DiligentGraphics** [comment]
Diligent Engine now supports [loading GLTF2.0 models](https://github.com/DiligentGraphics/DiligentSamples/tree/master/Samples/GLTFViewer), including animated objects. If you need to render animation and dump frames into images, you can follow [instructions here](https://github.com/DiligentGraphics/DiligentSamples#build-and-run-instructions).
