### ISSUE TITLE
Build failure on linux

### ISSUE THREAD

**Issue by Colins2** [DiligentGraphics/DiligentEngine#264]
I had a build failure in the module "Validating DiligentCore module's source code formatting."
The error was 'validate_format_linux_implementation.sh: Line 38: python: command not found
The file is: ...../DiligentEngine/DiligentCore/BuildTools/FormatValidation/validate_format_linux_implementation.sh
I changed 'python' to 'python3' on line 38 and then everything built normally.

**Comment by TheMostDiligent** [comment]
With [this change](https://github.com/DiligentGraphics/DiligentEngine/commit/9943185b017b869ad8061b454cc1ea83f02180a6), source code formatting validation will be disabled by default, so this should not be an issue anymore.
