### ISSUE TITLE
Wordpress site hijacked

### ISSUE THREAD

**Issue by jbarthelmes** [DiligentGraphics/DiligentEngine#268]
Your wordpress site that is linked from the readme is being used for viagra SEO:
![Screenshot](https://github.com/DiligentGraphics/DiligentEngine/assets/615914/b26469ca-e502-41e1-83ab-9701a27de150)
That paragraph gets removed by JS, googlebot can see it: https://webcache.googleusercontent.com/search?q=cache:6nltil-cjgAJ:diligentgraphics.com/diligent-engine/&cd=8&hl=en&ct=clnk

**Comment by TheMostDiligent** [comment]
Thank you - I removed it.
