### ISSUE TITLE
Run unity demo

### ISSUE THREAD

**Issue by hanbim520** [DiligentGraphics/DiligentEngine#27]
Hello, this is the first time I have used your library. I have successfully compiled the Xcode project and looked at all the examples. But when I run the unit project, I found that the dynamic library of plugins lacks some dependencies. Do you have any exact documentation? I run on OSX, and I also publish ios. Looking at IOS project on xcode, I also lack dependency, resulting in null function pointer.

<img width="1244" alt="screen shot 2019-01-09 at 1 17 09 am" src="https://user-images.githubusercontent.com/7490792/50847361-60274600-13ac-11e9-81eb-b31612525585.png">

**Comment by hanbim520** [comment]
I used the demo of Curry to run. I want to use your library to do some project rendering, such as using the Sparse virtual texture technology solution.

![111](https://user-images.githubusercontent.com/7490792/50871270-1cf1c500-13f6-11e9-8a9e-7e7ce6b021da.png)

**Comment by DiligentGraphics** [comment]
Unity plugin seems to be working fine on MacOS now (91d13074d5c3acd938c1514de1bbb95f57e85736).

![image](https://user-images.githubusercontent.com/15135271/50947122-9539a400-1451-11e9-961b-42cff0fdfc6b.png)

Few things worth mentioning:
1. On MacOS, Diligent Engine integrates with Unity through OpenGL, which is on Mac is very old (4.1). Diligent supports Vulkan through MoltenVK, but there is no integration through Metal with Unity.
2. At the moment Diligent Engine does not support partially resident resources in common API. You can use interoperability with native APIs to implement them directly, but I don't know if this will work for you.
3. When you build the project, Diligent automatically copies plugin bundle to Unity project folder. I had some problems with debug version. Release works fine.
