### ISSUE TITLE
windows build error

### ISSUE THREAD

**Issue by zhaokaixs** [DiligentGraphics/DiligentEngine#272]
tag:2.5.3
![image](https://github.com/DiligentGraphics/DiligentEngine/assets/7833585/b873d128-c7fa-4c83-8927-3570ca85fea6)

**Comment by MikhailGorobets** [comment]
You need take the ast changes

**Comment by TheMostDiligent** [comment]
Like @MikhailGorobets mentioned, the version you were trying to build is two years old.
Please get the latest version.
