### ISSUE TITLE
Runtime detection of supported render systems

### ISSUE THREAD

**Issue by beezir** [DiligentGraphics/DiligentEngine#28]
I don't have a system where I can test this - is it safe to indicate potentially unavailable render systems are valid?  According to the samples, the available render systems are indicated at compile time by defining specific macros.  I would like to default to D3D12, fall back to Vulkan, D3D11, etc., based on the system capabilities, but I don't have any way to test if that's safe or if I need to go with lowest common denominator, since my only dev system supports all of them.  

If it is valid to reference them on non-supported systems, is there a safe way to check at runtime which is the highest one available?

**Comment by DiligentGraphics** [comment]
You can check if the system can find the required dlls as in [the asteroids demo](https://github.com/DiligentGraphics/DiligentEngine/blob/master/Projects/Asteroids/src/WinWrapper.cpp#L398). If you build against Windows 8.1 SDK to support older platforms though, D3D12 is not available.

**Comment by DiligentGraphics** [comment]
Closing this for now. Please feel free to reopen/create a new issue if you have more questions.
