### ISSUE TITLE
Vulkan:  When running tutorial 12 (RenderTarget)  using Vulkan backend, you get errors on every frame

### ISSUE THREAD

**Issue by oferrun** [DiligentGraphics/DiligentEngine#282]
The following error is printed on every frame when running the RenderTarget Tutorial (12):

Diligent Engine: ERROR: Vulkan debug message (validation): VUID-vkCmdPipelineBarrier-srcStageMask-04095
                 Validation Error: [ VUID-vkCmdPipelineBarrier-srcStageMask-04095 ] Object 0: handle = 0x22c14beb1a0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x7e0d4050 | vkCmdPipelineBarrier(): .srcStageMask includes VK_PIPELINE_STAGE_MESH_SHADER_BIT_NV when the device does not have meshShader feature enabled. The Vulkan spec states: If the mesh shaders feature is not enabled, pname:srcStageMask must not contain VK_PIPELINE_STAGE_MESH_SHADER_BIT_NV (https://vulkan.lunarg.com/doc/view/1.2.198.1/windows/1.2-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-srcStageMask-04095)
                 Object[0] (cmd buffer): Handle 0x22c14beb1a0
Diligent Engine: ERROR: Vulkan debug message (validation): VUID-vkCmdPipelineBarrier-dstStageMask-04096
                 Validation Error: [ VUID-vkCmdPipelineBarrier-dstStageMask-04096 ] Object 0: handle = 0x22c14beb1a0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x87ffb8e9 | vkCmdPipelineBarrier(): .dstStageMask includes VK_PIPELINE_STAGE_TASK_SHADER_BIT_NV when the device does not have taskShader feature enabled. The Vulkan spec states: If the task shaders feature is not enabled, pname:dstStageMask must not contain VK_PIPELINE_STAGE_TASK_SHADER_BIT_NV (https://vulkan.lunarg.com/doc/view/1.2.198.1/windows/1.2-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-dstStageMask-04096)
                 Object[0] (cmd buffer): Handle 0x22c14beb1a0

Platform: Windows 10 x64
I am running with the latest Nvidia drivers on a 3070 RTX Nvidia GPU

**Comment by oferrun** [comment]
Some additional info:
Error is not printed using the DX12 backend.
I am building using Visual Studio 2022 Debug x64 build

**Comment by TheMostDiligent** [comment]
Does this only happen in tutorial 12 and not other tutorials?
Also, what version of Vulkan SDK are you using?

**Comment by oferrun** [comment]
After noticing it in tutorial 12 i looked for the errors in other tutorials.
Some have it only for a few frames and then it stops (tutorial 3 for example), yet others like 12, 27 post the error every frame.
I am using vulkan sdk version 1.2.198.1

Thanks for looking into it :)

**Comment by MikhailGorobets** [comment]
> After noticing it in tutorial 12 i looked for the errors in other tutorials. Some have it only for a few frames and then it stops (tutorial 3 for example), yet others like 12, 27 post the error every frame. I am using vulkan sdk version 1.2.198.1
> 
> Thanks for looking into it :)
It could be errors in the validation layers, this happens quite often. Try updating the Vulkan SDK and try again

**Comment by oferrun** [comment]
I did and it indeed solved the problem :)
Thanks!!!
