### ISSUE TITLE
Error building using MinGW-x64

### ISSUE THREAD

**Issue by TyrannusX** [DiligentGraphics/DiligentEngine#289]
Hello. I'm currently trying to build Diligent using MinGW-x64 (see below for compiler versions)

gcc.exe (GCC) 13.2.0
g++.exe (GCC) 13.2.0

I generated the makefile using CMake, but when running "make" it fails halfway with this error

[ 49%] Linking CXX static library libDiligent-GraphicsTools.a
[ 49%] Built target Diligent-GraphicsTools
[ 49%] Combining libraries...
C:\Apps\w64devkit\bin/ar.exe: *.obj: Invalid argument
make[2]: *** [DiligentCore\CMakeFiles\DiligentCore-static.dir\build.make:98: DiligentCore/libDiligentCore.a] Error 1
make[2]: *** Deleting file 'DiligentCore/libDiligentCore.a'
make[1]: *** [CMakeFiles\Makefile2:2188: DiligentCore/CMakeFiles/DiligentCore-static.dir/all] Error 2
make: *** [Makefile:155: all] Error 2

Any ideas?

**Comment by TheMostDiligent** [comment]
Our build on CI uses gcc 12.2.0 and [finishes successfully](https://github.com/DiligentGraphics/DiligentEngine/actions/runs/8956154633/job/24597639178#step:5:34)
Which distribution do you use? We test with [these](https://github.com/niXman/mingw-builds-binaries/releases)

**Comment by TyrannusX** [comment]
I'm using this one

https://github.com/skeeto/w64devkit

**Comment by TheMostDiligent** [comment]
Apparently, it does not have the `ar` utility.

**Comment by TyrannusX** [comment]
Hmm I ran ar.exe from the provided command line and it seems to work. Would MSYS2 work for building Diligent?

**Comment by TheMostDiligent** [comment]
You may try. There are too many distributions for us to try them all.
Note that MinGW is really not a recommended way to build the engine.

**Comment by TyrannusX** [comment]
Yes, thank you. I saw in the readme that MinGW was not recommended. I just prefer MinGW over MSVC/Visual Studio for Windows. Looks like using the distribution you recommended fixed my problem though!
