### ISSUE TITLE
Including BasicMath.h causes lots of errors???

### ISSUE THREAD

**Issue by ksidacroark** [DiligentGraphics/DiligentEngine#30]
when I include basicmath for float4 and Vector*<T> i get this http://prntscr.com/ma9r6e why is this happening?

**Comment by DiligentGraphics** [comment]
Generally Diligent headers require one of platforms macros (PLATFORM_WIN32, PLATFORM_LINUX) to be defined. If you use Cmake, these macros are exported by Diligent targets otherwise you need to define them.

**Comment by ksidacroark** [comment]
Yes - I already defined them beforehand - this is what my header looks like http://prntscr.com/mab4bv

**Comment by DiligentGraphics** [comment]
Can you post how you use it?

**Comment by DiligentGraphics** [comment]
Not sure why this happens, maybe some missing definitions. I need to take a closer look. Are you using Cmake?

**Comment by DiligentGraphics** [comment]
I double-checked an the header should work. In fact, there is even special [build test](https://github.com/DiligentGraphics/DiligentEngine/blob/master/Tests/IncludeTest/src/Common/BasicMathH_test.cpp) that only includes this single header. As long as platform definitions are properly defined, the header should work fine

**Comment by DiligentGraphics** [comment]
Is it possible that there are conflicts with other types? Math utils are not in Diligent namespace, which is an overlook and needs to be fixed https://github.com/DiligentGraphics/DiligentCore/issues/54

**Comment by DiligentGraphics** [comment]
Closing the issue for now. Please feel free to reopen or create another one if you still have problems.
