### ISSUE TITLE
USAGE type in GraphicsTypes.h conflicts with Windows' type USAGE found in hidusage.h

### ISSUE THREAD

**Issue by RevenantBob** [DiligentGraphics/DiligentEngine#300]
USAGE type in GraphicsTypes.h conflicts with Windows' type USAGE found in hidusage.h.

**Comment by RevenantBob** [comment]
I suppose it's in a namespace so probably fine.

**Comment by TheMostDiligent** [comment]
> I suppose it's in a namespace so probably fine.

Yes, this can easily be resolved using `Diligent::USAGE` and `::USAGE`
