### ISSUE TITLE
Link errors on MinGW

### ISSUE THREAD

**Issue by DiligentGraphics** [DiligentGraphics/DiligentEngine#31]
When building the engine on MinGW, some applications fail to link due to duplicate symbols coming from the import library, which makes no sense. The size of import libraries is ridiculous for DLLs exporting just one public symbol. Apparently there is an issue with the linker that adds a bunch of stuff to the import library even though all symbols are hidden.

https://stackoverflow.com/questions/54331717/duplicate-symbol-defined-in-a-dll-import-library-in-mingw-build

**Comment by logzero** [comment]
It is possible to tell the linker (ld) which symbols to export
https://stackoverflow.com/questions/435352/limiting-visibility-of-symbols-when-linking-shared-libraries

I've tried it with a simple test lib and it seems to work under mingw.

**Comment by TheMostDiligent** [comment]
I thought this is what I was doing with `-fvisibility=hidden` and `__attribute__((visibility("default")))`. However, this all made no difference.

**Comment by TheMostDiligent** [comment]
Did you manage to build Atmosphere sample?

**Comment by logzero** [comment]
Took me a bit of trial-and-error, but I've got it to run.

There is another issue though. The samples using xinput don't link against it (-lxinput).

**Comment by TheMostDiligent** [comment]
[This commit](https://github.com/DiligentGraphics/imgui/commit/11a3e75f47085fe14da5ff4ca5fe2298092fd937) fixes compile errors.
