### ISSUE TITLE
Is there a C API?

### ISSUE THREAD

**Issue by raizam** [DiligentGraphics/DiligentEngine#32]
Is it possible to create bindings?

**Comment by DiligentGraphics** [comment]
Yes, that should be feasible. Added an issue:
https://github.com/DiligentGraphics/DiligentCore/issues/55

**Comment by raizam** [comment]
I don't want to add more work on your shoulders, I'm just evaluating

**Comment by DiligentGraphics** [comment]
There have been multiple requests to add C API, so this is clearly an important feature. Most of Diligent API is structs and enums, so making them work in both c and c++ should be relatively easy. Interfaces will require more work though, but there are not so many of them.

**Comment by DiligentGraphics** [comment]
Closing this issue as there is one in Core module

**Comment by raizam** [comment]
just had a look but couldn't locate the C declarations, where can I find them?

**Comment by DiligentGraphics** [comment]
There is no C bindings yet. I closed this issues because I opened another issue in Core module DiligentGraphics/DiligentCore#55
