### ISSUE TITLE
VulkanDynamicMemoryManager leaking master blocks on OSX

### ISSUE THREAD

**Issue by philcn** [DiligentGraphics/DiligentEngine#33]
When I run the Tutorial02_Cube sample with latest master code, after a while, I start to get log messages of "Warning: Space in dynamic heap is almost exausted forcing mid-frame shrinkage. Increase the size of the heap buffer by setting EngineVkAttribs::DynamicHeapSize to a greater value or optimize dynamic resource usage", and I noticed its m_MasterBlockCounter keep going up every couple of frames. It seems that release of stale master blocks don't match with allocations. Is this a known issue?

Engine commit: c19a986065348039ea3eb44ad180c773f13f4a70
OS: macOS 10.14.1 beta
Computer: MacBook Pro, 15-inch, 2017 w/ Radeon Pro 555 gfx card

**Comment by DiligentGraphics** [comment]
Seems like Mac-specific problem. Will investigate.

**Comment by DiligentGraphics** [comment]
There was a bug: for invalid blocks the counter was incremented, but never decremented. That is fixed.
There however seems to be another issue: dynamic memory usage is too high (hence the warning messages). One potential reason could be that MoltenVK does not signal fences properly, so the memory is not recycled. This needs additional investigation.
