### ISSUE TITLE
can not build on mac

### ISSUE THREAD

**Issue by cailuming** [DiligentGraphics/DiligentEngine#35]
CMake Error at DiligentCore/External/CMakeLists.txt:6 (install):
  install TARGETS given target "glew-static" which does not exist in this
  directory.

CMake Error at DiligentCore/External/CMakeLists.txt:63 (install):
  install TARGETS given target "SPIRV-Tools" which does not exist in this
  directory.

**Comment by DiligentGraphics** [comment]
You need to update your CMake to the latest version.

**Comment by cailuming** [comment]
works now,  tks
