### ISSUE TITLE
D3D11: failed to create the swapchain

### ISSUE THREAD

**Issue by raizam** [DiligentGraphics/DiligentEngine#36]
I'm getting this error logged `Diligent Engine: ERROR in Diligent::EngineFactoryD3D11Impl::CreateSwapChainD3D11() (RenderDeviceFactoryD3D11.cpp, 355): Failed to create the swap chain`

then a null exception
`Exception thrown: read access violation.
this->m_pSwapChain.**m_pObject** was nullptr. occurred`

would be better to throw the exception right after create swapchain failure

**Comment by DiligentGraphics** [comment]
I do not think I fully understand the issue. If swap chain creation fails, an exception is thrown and then caught by the `CreateSwapChainD3D11()` function, which sets the pointer to null. The application should not use null pointer.

**Comment by raizam** [comment]
If it can help I'm on windows7, my system doesn't implement D3D11 1.1, I'm running 1.0.
I'll keep an eye on Diligent, but I'm going to wait it gets more stable before giving it another try.

**Comment by DiligentGraphics** [comment]
Again, not sure what you mean by D3D11 1.1. For render devices, Diligent creates feature level 11.0 device. It only tries to create feature level 11.1 device on Universal windows. But I assume that if you get an error during the swap chain initialization, the device has been created successfully. `IDXGIFactory2` seems to be supported on Windows7, so it is hard to tell what exactly is going wrong.
I don't have Windows7 so if you can give little bit more information, I may be able to fix this. Is there anything in the debug output?

**Comment by raizam** [comment]
of course you know I meant 11.1. Nothing in the debug output, here is a screenshot, I hope it helps
![untitled](https://user-images.githubusercontent.com/2153610/54047006-33d64d00-41d6-11e9-81d6-2f0c351a0c1f.png)

**Comment by DiligentGraphics** [comment]
Ok, it does show that the device has been created successfully, so it is not D3D11.1 issue. There should be something in the output, or if you can step into the `CreateSwapChainD3D11` function and see where exactly the error happens, this would be helpful.

**Comment by raizam** [comment]
I can't get GraphicsEngineD3D11_64d.pdb loaded, I don't know why

**Comment by DiligentGraphics** [comment]
Hmm. Not sure why this could be happening. You can try to link against static versions of libraries by changing get_default_library_type function in https://github.com/DiligentGraphics/DiligentCore/blob/master/BuildUtils.cmake

**Comment by arookas** [comment]
@DiligentGraphics I am also on Win7 x64 trying to run a tutorial ([specifically cube](https://github.com/DiligentGraphics/DiligentSamples/tree/master/Tutorials/Tutorial02_Cube)) with the 11.0 backend. I was able to get the runtime exception that occurs:

```
DXGI ERROR: IDXGIFactory::CreateSwapChain: DXGI_SCALING_NONE is only supported on Win8 and beyond. DXGI_SWAP_CHAIN_DESC{ SwapChainType = ..._HWND, BufferDesc = DXGI_MODE_DESC1{Width = 1280, Height = 1024, RefreshRate = DXGI_RATIONAL{ Numerator = 0, Denominator = 0 }, Format = R8G8B8A8_UNORM, ScanlineOrdering = ..._UNSPECIFIED, Scaling = ..._UNSPECIFIED, Stereo = FALSE }, SampleDesc = DXGI_SAMPLE_DESC{ Count = 1, Quality = 0 }, BufferUsage = 0x20, BufferCount = 2, OutputWindow = 0x00000000001F0480, Scaling = ..._NONE, Windowed = TRUE, SwapEffect = ..._FLIP_SEQUENTIAL, AlphaMode = ..._UNSPECIFIED, Flags = 0x2 } [ MISCELLANEOUS ERROR #175: ]
Exception thrown at 0x000007FEFD68BDED in Tutorial02_Cube.exe: Microsoft C++ exception: _com_error at memory location 0x00000000002DC670.
Diligent Engine: CRITICAL ERROR in Diligent::SwapChainD3DBase<class Diligent::ISwapChainD3D11,struct IDXGISwapChain>::CreateDXGISwapChain() (SwapChainD3DBase.h, 143): Failed to create Swap Chain
```

Seems to be missing support for `DXGI_SCALING_NONE` on Win7?

**Comment by DiligentGraphics** [comment]
Will take a look. Do other backends work?

**Comment by DiligentGraphics** [comment]
@arookas can you try other scaling modes and see if they work? I don't have Win7, so I will not be able to verify solutions.

**Comment by arookas** [comment]
@DiligentGraphics Thanks for the reply. I selected the OpenGL backend and it appears to run the demo just fine. My computer unfortunately support the other backends.

As for the scaling mode, I changed this line to the other scaling modes (`DXGI_SCALING_STRETCH` and `DXGI_SCALING_ASPECT_RATIO_STRETCH`) and they both make the demo run fine:

https://github.com/DiligentGraphics/DiligentCore/blob/d2b5a9c709d1a1e360aec0efa96d098a5b3569a2/Graphics/GraphicsEngineD3DBase/include/SwapChainD3DBase.h#L114

Is this scaling functionality specific to DirectX?

**Comment by DiligentGraphics** [comment]
Ok, good. TBH, I can't remember what implications different scaling modes have, will need to refresh this.

**Comment by DiligentGraphics** [comment]
@arookas This should hopefully fix the problem. Please reopen the issue if it still doesn't work.

**Comment by arookas** [comment]
@DiligentGraphics Works on my system. Thanks for your work!

**Comment by DiligentGraphics** [comment]
👍
