### ISSUE TITLE
Improve "API Basics" article

### ISSUE THREAD

**Issue by mctb32** [DiligentGraphics/DiligentEngine#4]
The article at http://diligentgraphics.com/diligent-engine/api-basics/ seems not up to date and has typos in the example code:
- EngineD3D12Attribs.member should be EngD3D12Attribs.member (repeats several times in the Win32 initialization example)
- The CreateDeviceAndSwapChainGL(...) does not take 5 params. The window handle is now passed via EngineGLAtribs. 

It would also be great if you could add a section on shutting down the engine.

**Comment by DiligentGraphics** [comment]
The page is indeed out-of-date. While I am updating it, you can take a look at
[Tutorial00_HelloWin32.cpp](https://github.com/DiligentGraphics/DiligentSamples/blob/master/Tutorials/Tutorial00_HelloWin32/src/Tutorial00_HelloWin32.cpp) and [Tutorial00_HelloLinux.cpp](https://github.com/DiligentGraphics/DiligentSamples/blob/master/Tutorials/Tutorial00_HelloLinux/src/Tutorial00_HelloLinux.cpp). The code is pretty much self-explanatory.

If you want to statically link with the engine, you will need to 
```cpp
#define ENGINE_DLL 0
```

The engine performs automatic reference counting, so it shuts down when the last reference to engine object is released.

**Comment by mctb32** [comment]
Thanks. I suspected that much about releasing the engine, just though it would be good to make a note about it in the API Basics section.
