### ISSUE TITLE
Occlusion query support?

### ISSUE THREAD

**Issue by yibbidy** [DiligentGraphics/DiligentEngine#48]
are there any plans to support occlusion queries?  

I'm interested in reworking a GL graphics engine which does occlusion culling via query objects.

**Comment by DiligentGraphics** [comment]
Yes, Occlusion queries are planned.
https://github.com/DiligentGraphics/DiligentCore/issues/25

**Comment by yibbidy** [comment]
Ah, didn't think to search the DiligentCore project for answers.  Thanks.
