### ISSUE TITLE
Linux compile error

### ISSUE THREAD

**Issue by ChristofferGreen** [DiligentGraphics/DiligentEngine#51]
System:Ubuntu 18.04.2 LTS (Bionic Beaver)

Commandlog:
git clone --recursive https://github.com/DiligentGraphics/DiligentEngine.git
cd DiligentEngine
mkdir build
cd build
cmake ../
make

Result:
`[  2%] Building CXX object DiligentCore/External/glslang/hlsl/CMakeFiles/HLSL.dir/hlslAttributes.cpp.o
Scanning dependencies of target spirv-cross-core

[  2%] Building CXX object DiligentCore/External/SPIRV-Cross/CMakeFiles/spirv-cross-core.dir/spirv_cross.cpp.o

[  2%] Linking CXX static library libOSDependent.a

[  2%] Built target enum_string_mapping

[  2%] Building CXX object DiligentCore/External/SPIRV-Cross/CMakeFiles/spirv-cross-core.dir/spirv_parser.cpp.o

[  2%] Built target OSDependent

[  2%] Building CXX object DiligentCore/External/SPIRV-Cross/CMakeFiles/spirv-cross-core.dir/spirv_cross_parsed_ir.cpp.o
Traceback (most recent call last):
  File "/docs/src/DiligentEngine/DiligentCore/External/SPIRV-Tools/utils/generate_registry_tables.py", line 19, in <module>
    import distutils.dir_util

ModuleNotFoundError: No module named 'distutils.dir_util'

DiligentCore/External/SPIRV-Tools/source/CMakeFiles/core_tables.dir/build.make:72: recipe for target 'DiligentCore/External/SPIRV-Tools/generators.inc' failed

make[2]: *** [DiligentCore/External/SPIRV-Tools/generators.inc] Error 1
CMakeFiles/Makefile2:466: recipe for target 'DiligentCore/External/SPIRV-Tools/source/CMakeFiles/core_tables.dir/all' failed

make[1]: *** [DiligentCore/External/SPIRV-Tools/source/CMakeFiles/core_tables.dir/all] Error 2

make[1]: *** Waiting for unfinished jobs....
`

**Comment by ChristofferGreen** [comment]
Solved by: 'sudo apt-get install python3-distutils'

Perhaps CMake should check if distutils are installed during configure step?

**Comment by DiligentGraphics** [comment]
@ChristofferGreen Is this package not part of the python installation?

**Comment by ChristofferGreen** [comment]
I'm not an expert in these things but it does not look that way:

https://packages.debian.org/sid/python3

has no dependency towards

https://packages.debian.org/sid/python3-distutils
