### ISSUE TITLE
Memory managers question

### ISSUE THREAD

**Issue by ivalylo** [DiligentGraphics/DiligentEngine#52]
Hello,

This is more like a question, but how the internal memory managers compare to VulkanMemoryAllocator / D3D12MemoryAllocator. Did you have a chance to test if it's worth integrating them? I'm not familiar with these libraries. Just read the implementation in Diligent Engine, and I was wondering what such bigger libraries can do better.

**Comment by DiligentGraphics** [comment]
I did not look specifically at VulkanMemoryAllocator, but from presentations/talks I understand that it wraps things like memory type, alignment, page size, etc. Memory allocation system in Diligent is specifically designed for the API model and works well. There is no obvious problem that would be solved by integrating VulkanMemoryAllocator / D3D12MemoryAllocator. If such problem arises, it would be reasonable to take ideas from these libraries, but before then there is a lot of more important things to work on.

**Comment by ivalylo** [comment]
I'm asking since the engine seems to put big emphasis on memory allocations. AFAIK, the VulkanMemoryAllocator promotes more advanced defragmentation features, although I can see thay by design Diligent has a separate gpu heap allocator which probably handles most causes of fragmentation. Anyway, I was just curious how this works since I have no experience with Vulkan/D3D12, and this manual memory management thing is really the "meat" of a modern engine.

**Comment by DiligentGraphics** [comment]
There is no magic solution to defragmentation problem and it is not correct to expect that Diligent, VulkanMemoryAllocator  or D3D12MemoryAllocator will be able to solve the problem completely. With low-level APIs it is the ultimate responsibility of the application to allocate resources in a way that avoids fragmentation. The good news is that everything is explicit and if there is a problem, it is possible to update the engine / tweak the application.
