### ISSUE TITLE
error cmake + Visual Studio 2019

### ISSUE THREAD

**Issue by JavierMaura** [DiligentGraphics/DiligentEngine#54]
Sorry, but i can not generate it. Neither using GUI... :(

cmake -S . -B ./build/Win64 -G "Visual Studio 16 2019" -A x64

CMake Error at CMakeLists.txt:5 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.

Configuring incomplete, errors occurred!

**Comment by DiligentGraphics** [comment]
This does not look like a project issue: CMake is unable to find Visual Studio before even starting to look at the engine files. Looks like there is a problem with your system configuration. Which version of Visual Studio do you have installed?

**Comment by DiligentGraphics** [comment]
This may be useful for you:
https://stackoverflow.com/questions/51668676/cmake-visual-studio-15-2017-could-not-find-any-instance-of-visual-studio

My guess is that when you installed visual studio, you may not have selected c++ development tools. Double check that

**Comment by JavierMaura** [comment]
You were right!!! Awesome!!
