### ISSUE TITLE
Android win10 "The command line is too long."

### ISSUE THREAD

**Issue by adamikandras** [DiligentGraphics/DiligentEngine#55]
I've tried to compile the Android project on win10, but unfortunately this error keeps coming up: "The command line is too long.", because the ninja script tries to compile a lot of things at once.
Can you give some advice on how to tackle this problem?
I'd really like to try it out on Android, and I couldn't figure out, how to fix this problem.
Has anyone faced this issue before?

**Comment by DiligentGraphics** [comment]
Try to clone the source to a directory with short name such as c:\git

**Comment by adamikandras** [comment]
@DiligentGraphics
Thanks, I thought about it as well, but still doesn't work.
Have you tried to compile it on Win for Android?
I believe the solution should be something like reducing/reorganizing the dependencies/parallel project builds, because right now really a lot of build commands are merged together with "&&"-s on a single line in the actual resulting build command.
Maybe using powershell, or smth else instead of cmd.exe would help as well. Maybe that allows longer single line commands (right now it is 16840 chars long for me on a single line :O :O).
Unfortunately I don't really know whether it is possible to configure the used shell, or the parallel builds, this is why I'm asking for help. I was hoping someone has already fixed this somehow.
Thanks in advance!

**Repro:** 
1. _clone main head into c:/git/DiligentEngine on Windows_
2. _open C:/git/DiligentEngine/DiligentSamples/Android in AndroidStudio_
3. _build project_
4. _"FAILED: DiligentFX/CMakeFiles/DiligentFXCustomCommands.util The command line is too long."_

**Comment by DiligentGraphics** [comment]
This appears to be a known limitation of ninja. I tried to use the solution from [here](https://stackoverflow.com/a/53750480/4347276), but it did not work. You can try to experiment with build.gradle file of Common module.
To make the build work, you can disable the FX module:
add '-DDILIGENT_BUILD_FX=FALSE' to the command line arguments in the Common's build.gradle.
 As a result, GLTF viewer, shadows and atmosphere samples will not work, but imgui and all tutorials should run fine.

**Comment by adamikandras** [comment]
@DiligentGraphics 
Thanks for the tip, but it didn't really work out, so I fixed it myself. The main problem was that the ninja build handled the multiple build commands for a given target as one in a single line for DiligentFX. So I broke them up and moved the build target definition inside the loop, which resulted in one target per command, but this way it doesn't exceed the command line limit.
With this the whole project compiles successfully in Android Studio, but sadly when I tried to start it, the app crashed every time. After a little brainstorming I figured out, that for some reason the *.so files were stripped out of the *.apk and because of that it couldn't load the symbols during runtime. I tried to set doNotStrip in build.gradle in every place, but none of them helped. Anyway I noticed, that when I simply build the app with the build command instead of the start, or debug buttons, the resulting *.apk contains every needed *.so files. So when I manually installed these *.apk files on the phone, the examples worked like a charm.
I really wanted to check the GLTFViewer, because I liked this possibility a lot, but I think if someone has less determination, maybe they would give up trying. I think the whole project setup is nice for Android and I can see a lot of work went into it, so if these problems would be fixed, maybe more people would get involved with this engine.

**Comment by DiligentGraphics** [comment]
@adamikandras Could you by any chance try to build this on Linux or Mac because this is the main way people usually build for Android? Everything should work out-of-the-box.
Android build on Windows has always been problematic and very slow. I tried to support it for some time but eventually gave up.
Thanks for the hint about one target per file. Does it generate a ton of projects in Visual Studio solution BTW?
As to stripping *.so from the apk depending on how you build the project, looks like Android Studio configuration issue, I've never seen this before (on Linux or Mac).

**Comment by adamikandras** [comment]
@DiligentGraphics 
I thought so that it was tested on Linux rather than Windows, but I think that is a very popular platform as well. Anyways I'm glad to hear that it should work better on Linux, I'll give it a shot sometime in the near future.
As per the one-target-per-file: it generated a new project for every shader in the DiligentFX project. :/
Firstly I wanted to create only two targets by halving the shader list which would be a little better solution than this, but unfortunately the sublist feature for CMake came in a later version, so it was simpler to move the existing code into the foreach.

**Comment by DiligentGraphics** [comment]
I totally agree that Windows is a very popular platform (and also the best), I personally do all development on Windows and only enable other platforms. But for Google, Windows is a second-class citizen platform, so it is not a surprise there are issues in Android Studio on Windows.

**Comment by Hyrtwol** [comment]
maybe try to enable long paths (did test it so can't promise anything :p)
https://winaero.com/blog/how-to-enable-ntfs-long-paths-in-windows-10/
if i remeber right the latest python installer also offer this fix during installation

**Comment by DiligentGraphics** [comment]
This change should fix this problem:
https://github.com/DiligentGraphics/DiligentFX/commit/7c39e3e4d838cf8ef56fd59d82936f8ca3fcb0e0
Instead of one giant command, there are now individual commands for every file. I was successfully able to build for Android on Windows.
