### ISSUE TITLE
Make it catch DX12 not existing

### ISSUE THREAD

**Issue by indi-code** [DiligentGraphics/DiligentEngine#62]
My computer has the dx12 dll but cant support DirectX 12. Mabe find a better way to check than just searching for DLLs

**Comment by DiligentGraphics** [comment]
Your system supports Direct3D12 API (so the dll is there), but your GPU does not.
The apps should at least show an error message.

**Comment by indi-code** [comment]
None of the error messages make much sense unless you look through the call stack, and theres gotta be some way to catch it and just use DX11

**Comment by DiligentGraphics** [comment]
> and theres gotta be some way to catch it and just use DX11

This exactly how it works now. If there is no D3D12, it will attempt to initialize in D3D11 mode. Any Windows more up to date than Windows 95 supports D3D11.
Similar with Vulkan. If it fails to run in Vulkan mode, it will attempt to run in OpenGL mode.

**Comment by indi-code** [comment]
> but your GPU does not.
Is there any way i can catch this from inside my game? The GPU not supporting it? Instead of crashing?

**Comment by DiligentGraphics** [comment]
If your GPU does not support D3D12, you will fail to initialize D3D12 back-end. This is how you catch it. You can then initialize D3D11 backend.
For D3D11 and D3D12, you can also enumerate available adapters. If you have 0, that means there is no compatible adapters.
Take a look [here](https://github.com/DiligentGraphics/DiligentSamples/blob/master/Samples/SampleBase/src/SampleApp.cpp#L186)

**Comment by indi-code** [comment]
thanks. Why isn't this implemented by default though?

**Comment by DiligentGraphics** [comment]
This is implemented by default as of the commit that closed this issue.

**Comment by indi-code** [comment]
Oh, sorry, didnt see that
thanks :D
