### ISSUE TITLE
cpp17

### ISSUE THREAD

**Issue by justkarli** [DiligentGraphics/DiligentEngine#67]
Hi, 
I want to ask if u have tried DiligentCore with c++17? 
I've tried integratting DiligentCore with a few of our libraries, but we are already using std::filesystem. 

When I define cxx standard in cmake to 17
```
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```

I'll get the following error when compiling the project

```
Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\map(448): error C2338: multimap<Key, Value, Compare, Allocator> requires that Allocator's value_type match pair<const Key, Value> (See N4659 26.2.1 [container.requirements.general]/16 allocator_type) Either fix the allocator value_type or define _ENFORCE_MATCHING_ALLOCATORS=0 to suppress this diagnostic.
```
pointing to the file
- D3D12DynamicHeap.h(152)

Cheers, 
karli

**Comment by DiligentGraphics** [comment]
Can you for the sake of experiment try to add `const` before `Uint64` at line 151 as follows:
```cpp
using AvailablePagesMapElemType = std::pair<const Uint64, D3D12DynamicPage>
```

**Comment by justkarli** [comment]
nice, that worked! But another error is still occuring, seems that it is looking for a default ctor: 

```
ShaderResourceLayoutD3D12.cpp(678): error C2512: 'Diligent::ShaderResourceCacheD3D12::Resource': no appropriate default constructor available
```

Thank you!

**Comment by DiligentGraphics** [comment]
Ok, I think there will be a number of minor issues that need to be fixed. Will take a look.

**Comment by DiligentGraphics** [comment]
c++17 should now work fine (at least in Visual Studio 2019)

**Comment by justkarli** [comment]
nice, I'll try it asap! :) Thank you!
