### ISSUE TITLE
Why can't map a vulkan buffer to read?

### ISSUE THREAD

**Issue by hzsoft312** [DiligentGraphics/DiligentEngine#69]
When I map a buffer for reading using Vulkan API, the code says:
LOG_ERROR("Mapping buffer for reading is not yet imlemented in Vulkan backend");

So is there a way to read the content of a staging vulkan buffer?

**Comment by DiligentGraphics** [comment]
This is not yet implemented, will fix

**Comment by DiligentGraphics** [comment]
Fixed by https://github.com/DiligentGraphics/DiligentCore/commit/d4b8e0c30214065e63d428be3219f6db18e02a2d
