### ISSUE TITLE
Is there any open source project using DiligentEngine?

### ISSUE THREAD

**Issue by mindoff6502** [DiligentGraphics/DiligentEngine#73]
Learning DiligentEngine and bgfx,both have good examples.
Yet bgfx has some open source project can be found on github.
DiligentEngine still doesn't.
Want to see how people use it in real life.

**Comment by DiligentGraphics** [comment]
There are a number of commercial projects that use Diligent. There may be open source projects, but I am not aware.

**Comment by DiligentGraphics** [comment]
Closing this issue as there is nothing actionable that can be done.
