### ISSUE TITLE
How to change font with Imgui?

### ISSUE THREAD

**Issue by mindoff6502** [DiligentGraphics/DiligentEngine#74]
This is not a DiligentEngine problem I think,but I really don't know how to do this.
In original imgui example,he writes some implments for DX11,opengl for glfw and sdl2.
Just add those file to project and call then I can add new font freely.
But I didn't find such thing in DiligentEngine or bgfx,and call
io.Fonts->AddFontFromFileTTF
always crash.

Example
In DiligentEngine ImguiDemo

call
ImGuiIO& io = ImGui::GetIO(); (void)io;
io.Fonts->AddFontFromFileTTF("somefont.ttf", 24.0f, nullptr, io.Fonts->GetGlyphRangesDefault());

before
SampleBase::Initialize(pEngineFactory, pDevice, ppContexts, NumDeferredCtx, pSwapChain);

always crash

So what should I do if I want to add imgui font in DiligentEngine the correct way?

And after some test,found a dirty hack way for changing font once.
In this file
DiligentTools\ThirdParty\imgui\imgui_draw.cpp
search for AddFontDefault
call something like

ImFont* font = AddFontFromFileTTF("somefont.ttf", 24.0f, nullptr, GetGlyphRangesDefault());
return font;

This will change the font for the first time.Dirty but work.
Still, I need to change ImGUI font in real time,any better ways to do this?

The problem is in ImGUI original example,I add font before the main loop,everything works fine.
But in DiligentEngine I add font always crash.

**Comment by DiligentGraphics** [comment]
I honestly don't know the answer to this question as like you mentioned, it is related to dear imgui. One thing is that you likely need to call `CreateFontsTexture()` after you add new font.
But like I said, I don't know how to work with fonts in dear imgui.

**Comment by mindoff6502** [comment]
OK,after trace from imgui dx11 and glfw sdl opengl example,
I think I know where the problem is.


I think your file
DiligentTools\Imgui\src\ImGuiImplDiligent.cpp

Did an early ImGui_ImplXXX_NewFrame which original dx11 called ImGui_ImplDX11_NewFrame
and opengl called ImGui_ImplOpenGL3_NewFrame

which actually is calling function XXX_CreateDeviceObjects

this XXX_CreateDeviceObjects should be called each frame in the main loop,
should not be called right after ImGui_ImplWin32_Init or things like this.

You're doing this like below

OnWindowCreated
	m_pImGui.reset(new ImGuiImplWin32(m_hWnd, m_pDevice, SCDesc.ColorBufferFormat, SCDesc.DepthBufferFormat));
		ImGuiImplDiligent{pDevice, BackBufferFmt, DepthBufferFmt, InitialVertexBufferSize, InitialIndexBufferSize}
			m_pImpl(new ImGuiImplDiligent_Internal(pDevice, BackBufferFmt, DepthBufferFmt, InitialVertexBufferSize, InitialIndexBufferSize))
				CreateDeviceObjects();
					CreateFontsTexture();
						io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height);
							GetTexDataAsAlpha8(&pixels, NULL, NULL);
								AddFontDefault
								
which will trigger add default imgui font before user can add custom font by calling
io.Fonts->AddFontFromFileTTF


so this different early creation and init lead to the difference between original imgui example and your
imgui example

maybe you can make some change to match exact the same to original imgui style?

**Comment by DiligentGraphics** [comment]
Last-minute resource creation is not a good practice and is avoided as much as possible in Diligent Engine, which is why Imgui is initialized up front. 
Like I mentioned, all you likely need to do is to call `CreateFontsTexture()` after you uploaded your font.

**Comment by DiligentGraphics** [comment]
You can load a new font by modifying [SampleApp::InitializeSample()](https://github.com/DiligentGraphics/DiligentSamples/blob/master/SampleBase/src/SampleApp.cpp#L380) as follows:

```cpp
void SampleApp::InitializeSample()
{
    auto& io = ImGui::GetIO();
    io.Fonts->AddFontFromFileTTF(R"(E:\_asset\font\DroidSansFallback.ttf)", 24.0f);
    io.FontDefault = io.Fonts->Fonts[1];
    m_pImGui->UpdateFontsTexture();
    ...
```

**Comment by DiligentGraphics** [comment]
So now you can write the following to load your fonts:

```cpp
void YourSample::Initialize(const SampleInitInfo& InitInfo)
{
    SampleBase::Initialize(InitInfo);

    auto& io = ImGui::GetIO();
    io.Fonts->AddFontFromFileTTF(R"(E:\_asset\font\DroidSansFallback.ttf)", 24.0f);
    io.FontDefault = io.Fonts->Fonts[1];
    m_pImGui->UpdateFontsTexture();
}
```

**Comment by mindoff6502** [comment]
Thnaks for the update,works fine now.
