### ISSUE TITLE
Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at   least version "3")

### ISSUE THREAD

**Issue by SC5Shout** [DiligentGraphics/DiligentEngine#76]
I downloaded repo through github desktop, opened cmd and typed
> cd DiligentEngine
> cmake -S . -B ./build/Win64 -G "Visual Studio 16 2019" -A x64

and I've got this error 
![image](https://user-images.githubusercontent.com/43299401/76882822-7e73b600-687b-11ea-9917-59ad609f5087.png)

outputlog: 
[CMakeOutput.log](https://github.com/DiligentGraphics/DiligentEngine/files/4344792/CMakeOutput.log)

I use the latest cmake version. Do you know how to fix this problem?

**Comment by TheMostDiligent** [comment]
Like [build instructions](https://github.com/DiligentGraphics/DiligentEngine#build-and-run-instructions) explain, you need to have Python installed on your system.

**Comment by SC5Shout** [comment]
Oh, I read instructions 100 times and did not see that. I am so sorry.

**Comment by TheMostDiligent** [comment]
No worries. You can also ask questions on [gitter](https://gitter.im/diligent-engine/Lobby).
