### ISSUE TITLE
How to update cubemap

### ISSUE THREAD

**Issue by carlcc** [DiligentGraphics/DiligentEngine#77]
Hi,

Is there an exact example of updating a cube map (used to render point light shadow)? I didn't any in all examples. I am not sure what is the right way to do that...

**Comment by TheMostDiligent** [comment]
There is no tutorial specifically for cubemap rendering, but it is not much different from rendering to a texture array: you create a cubemap texture and then create render target view for evey of its faces. Or, alternatively, you can create a RTV for entire cubemap and then select the face in geometry shader.
You can find any example on the web, they will translate directly to Diligent.

**Comment by carlcc** [comment]
Hi,

I have wrote a short test program, I think it's almost done, but I found OpenGL behaves not as I expected. I am not sure if this is a bug, or just simply because 'OpenGL does not support treating cube map as a texture array'?

The program create a cube map, and use its 1st slice as an off-screen depth buffer, and render the depth buffer on the surface of the cubes in the main view port.

DX11, DX12 and VK:
![image](https://user-images.githubusercontent.com/12776190/77334516-e0428d00-6d5f-11ea-9162-8c5467c0d228.png)

OGL:
![image](https://user-images.githubusercontent.com/12776190/77334599-ffd9b580-6d5f-11ea-8d70-5da5b1a26b5d.png)


The following is my code:

[code.zip](https://github.com/DiligentGraphics/DiligentEngine/files/4370375/code.zip)

**Comment by TheMostDiligent** [comment]
So only OpenGL version works the way you expect?

**Comment by carlcc** [comment]
No... Only opengl version NOT works as I expect

**Comment by TheMostDiligent** [comment]
Are you running debug build? Do you have any message in the output? Which OpenGL version does your device support?
OpenGL may not allow Texture2D view of a cubemap texture

**Comment by carlcc** [comment]
Yeah, debug build, but there is no warning nor error log message in the output.

Initialized OpenGL 4.4 context (4.4.0 NVIDIA 417.22)
Info: GPU Vendor: nvidia corporation

My environment:
Visual Studio 2017 Community
Nvidia GTX960M
Windows 10 Pro 18362.720

Do I need to post all my runnable code here?

**Comment by TheMostDiligent** [comment]
Hm, OpenGL 4.4 should support texture views. Can you try to create a cubemap view for your texture and see if that works?

**Comment by carlcc** [comment]
Seems to be worse... All the backends become not working

**Comment by TheMostDiligent** [comment]
Actually, I completely forgot. Take a look at how GLTF renderer precomputes cube maps:
https://github.com/DiligentGraphics/DiligentFX/blob/master/GLTF_PBR_Renderer/src/GLTF_PBR_Renderer.cpp#L588
This works in all backends.

**Comment by carlcc** [comment]
Sorry for my finishing this thread so late, but indeed, it works. 

**All we need to do is updating each slice of a cube map.**

I hope this will help those who have the same question.
