### ISSUE TITLE
Allow usage of system clang-format instead of bundled.

### ISSUE THREAD

**Issue by markusgod** [DiligentGraphics/DiligentEngine#79]
- OS and version **Fedora 32**
- Build tools and configuration you used to build the engine **Clion, clang-10,  cmake 3.17.2**
- Debug output, especially messages from Diligent
```
./clang-format_linux_10.0.0: /lib64/libtinfo.so.5: no version information available (required by ./clang-format_linux_10.0.0)
```

**Comment by TheMostDiligent** [comment]
Do you get this error when you attempt to run the build?

**Comment by markusgod** [comment]
Exactly, and if i replace it this system clang format everything runs just fine.

**Comment by TheMostDiligent** [comment]
OK, I see. Will take a look

**Comment by markusgod** [comment]
it looks like your binary requires libtinfo.so to be in /lib64/ while in fedora it installed to /usr/lib64/ using ncurses-compat-libs package. symlink is a possible workaround, but to me using system binary if possible is preferable option.
![screenshot1](https://i.imgur.com/S4sKu46.png)
![screenshot2](https://i.imgur.com/jPd68QJ.png)
https://fedora.pkgs.org/32/fedora-x86_64/ncurses-compat-libs-6.1-15.20191109.fc32.x86_64.rpm.html

**Comment by TheMostDiligent** [comment]
One reason I use bundled binary is because it is important to stick to a specific version of clang-format. Another reason is that it requires less effort to build the engine (when it works though): having clang on the system is not a requirement.
I will change CMake instructions to use bundled version on Ubuntu and system binary on other distributions.

**Comment by dpellegr** [comment]
I am having the same issue on Arch, `libtinfo.so.5` is gone, I only have v6:
```
$ find /usr -name 'libtinfo*' 
/usr/lib/libtinfo.so
/usr/lib/libtinfo.so.6
```
I also have clang installed system-wide (for many other projects) so it is really easy for me to move on, but how important is it to stick to a specific version of `clang-format`?

**Comment by TheMostDiligent** [comment]
> how important is it to stick to a specific version

Format validation is performed by CI server on every commit. The build will fail if any formatting issues are found, so it is essential that local formatting produces exactly the same results. As formatting performed by `clang-format` is not consistent between version, it is pretty important to stick to a specific version.

Maybe somebody can take time to update [this script](https://github.com/DiligentGraphics/DiligentCore/blob/master/BuildTools/FormatValidation/validate_format_linux.sh) to check if clang-format is already installed on the system and if the version matches, and use it in this case. If the version does not match, resort to the pre-installed one.

**Comment by dpellegr** [comment]
> Maybe somebody can take time to update [this script](https://github.com/DiligentGraphics/DiligentCore/blob/master/BuildTools/FormatValidation/validate_format_linux.sh) to check if clang-format is already installed on the system and if the version matches, and use it in this case. If the version does not match, resort to the pre-installed one.

I had a look at it and I think that it wouldn't be hard for me to produce a pull request.

However I am not sure about the logic that you are proposing. My clang-format version is 10.0.1 which is different from the one currently shipped with Diligent. Therefore, according to your proposal, I should resort to the latter, which on my system will fail as `libtinfo.so.5` is not available. On the other hand I have compiled the engine and the demos perfectly fine with my version. 

Maybe the script should first try to load the shipped bin, and if that fails, search for a system bin and try with that no matter what version. Should I proceed in this way?

**Comment by TheMostDiligent** [comment]
> Maybe the script should first try to load the shipped bin, and if that fails, search for a system bin and try with that no matter what version. Should I proceed in this way?

Yes, I was going to suggest exactly the same thing: first try to run the bundled version (maybe check if `clang-format -v` succeeds?). Then check the system clang-format. If version is not the same, proceed, but output a warning message that formatting result may differ from the bundled version. If there is no suitable binary, output a warning and skip validation completely (I think this is better than failed build).

**Comment by TheMostDiligent** [comment]
Fixed in https://github.com/DiligentGraphics/DiligentCore/pull/154 (credit to @dpellegr!)

**Comment by dpellegr** [comment]
Awh, what about [this one](https://github.com/DiligentGraphics/DiligentTools/blob/master/BuildTools/FormatValidation/validate_format_linux.sh)? Now it gets stuck on that... Should we move the bin search in a separated script sourced by both the validation scripts?

**Comment by TheMostDiligent** [comment]
> Awh, what about [this one](https://github.com/DiligentGraphics/DiligentTools/blob/master/BuildTools/FormatValidation/validate_format_linux.sh)?

Ooops, I completely forgot about other submodules, which all run format validation too. There are also similar scripts in [FX](https://github.com/DiligentGraphics/DiligentFX/blob/master/BuildTools/FormatValidation/validate_format_linux.sh) and [Samples](https://github.com/DiligentGraphics/DiligentSamples/blob/master/BuildTools/FormatValidation/validate_format_linux.sh) modules.


> Should we move the bin search in a separated script sourced by both the validation scripts?

Yes, this is definitely what we should do. I think [this](https://github.com/DiligentGraphics/DiligentCore/blob/master/BuildTools/FormatValidation/validate_format_linux.sh#L1-L27) should be a separate script (run_clang_format_linux?), which validate_format_linux should call and pass the list of directories. The only thing to be careful about is returning the error code to the parent shell. I remember I was having really hard times trying to make this work, but linux shell is not my strongest part for sure.

**Comment by TheMostDiligent** [comment]
@dpellegr Thanks for the fix! Could you please update other submodules: [Tools](https://github.com/DiligentGraphics/DiligentTools/blob/master/BuildTools/FormatValidation/validate_format_linux.sh), [FX](https://github.com/DiligentGraphics/DiligentFX/blob/master/BuildTools/FormatValidation/validate_format_linux.sh), [Samples](https://github.com/DiligentGraphics/DiligentSamples/blob/master/BuildTools/FormatValidation/validate_format_linux.sh)?

**Comment by TheMostDiligent** [comment]
As of https://github.com/DiligentGraphics/DiligentEngine/commit/61810e5272730ddfea158d8d4e572cafcea68941 this should be fixed for good. @dpellegr let me know if you still have problems.

**Comment by theoparis** [comment]
Unfortunately I am still getting build errors due to clang-format and libtinfo, 2 years later 😕 

```
Generate CXX -> CommonParser.hpp
/home/theo/dev/DiligentEngine/DiligentTools/RenderStateNotation/../../DiligentCore/BuildTools/FormatValidation/clang-format_linux_10.0.0: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
[578/703] Building C...src/GLTFLoader.cpp.
```

Using the `ln -s` solution provided earlier seems to fix it for now though.

**Comment by TheMostDiligent** [comment]
There is pending fix for this, but it requires some set up changes.

**Comment by lindemeier** [comment]
I get the error with that setup:

-     Ubuntu 24.04
-     gcc 13.2.0,  cmake version 3.28.3, clang version 18.1.3

```bash
.../DiligentEngine/DiligentCore/BuildTools/FormatValidation/clang-format_linux_10.0.0: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
gmake[2]: *** [DiligentTools/RenderStateNotation/CMakeFiles/Diligent-RenderStateNotation.dir/build.make:86: DiligentTools/RenderStateNotation/parser_headers/generated/BlendStateParser.hpp] Error 127
gmake[2]: *** Deleting file 'DiligentTools/RenderStateNotation/parser_headers/generated/BlendStateParser.hpp'
gmake[1]: *** [CMakeFiles/Makefile2:4633: DiligentTools/RenderStateNotation/CMakeFiles/Diligent-RenderStateNotation.dir/all] Error 2

```

**Comment by TheMostDiligent** [comment]
Issues on Ubuntu 24.04 have been fixed
