### ISSUE TITLE
Make swapchain's color texture accessible

### ISSUE THREAD

**Issue by hals1010** [DiligentGraphics/DiligentEngine#8]
For some post-processing / Direct2D stuff, I would like to access the color texture(s) of a swap chain.

So, something like:

`void ISwapChain::GetTexture(Uint32 BufferIndex, ITexture** ppTexture2D)`

Regards,
Jörn

**Comment by DiligentGraphics** [comment]
This type of function will not be portable across APIs as OpenGL/GLES only gives you FBO handle and you cannot access the internal texture (at least I do not know the way to achieve this). You can use API-specific interfaces such ISwapChainD3D11/12 to access the dxgi swap chain object and depth buffer, or ISwapChainOpenGL to get default FBO handle.

**Comment by DiligentGraphics** [comment]
Closing the issue due to the reasons above
