### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by markusgod** [DiligentGraphics/DiligentEngine#80]
It would be nice to have a conan.io package.
Here what i currently managed to achieve. But I'm a bit lost in end user cmake targets and libraries to link against.
https://github.com/markusgod/DiligentEngine-conan/tree/master

**Comment by markusgod** [comment]
@TheMostDiligent can you please take a look and check if guys at conan found all dependencies for your engine?
conan-io/conan-center-index#1533

**Comment by TheMostDiligent** [comment]
@markusgod How exactly does Conan handle dependencies?
The engine has all the required third-party libraries as submodules, and few smaller ones are just checked into the codebase. Cloning the repo recursively pulls all the dependencies.

**Comment by markusgod** [comment]
conan pulls dependencies (source for local build or precompiled binaries if available) that declared in [conanfile.txt/py](https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#) that later will be injected to the build system [using generators](https://docs.conan.io/en/latest/reference/generators.html). [Conan package (recepie)](https://docs.conan.io/en/latest/creating_packages/external_repo.html) itself is a python script that pull sources from git/tar/etc and specifies how it should be built. There are also fancy [context stuff](https://blog.conan.io/2020/04/06/New-conan-release-1-24.html) that allows to specify what package need only for build and won't need after compilation, but I'm not experienced enough with it.

**Comment by TheMostDiligent** [comment]
If Conan can do `git clone --recursive`, that would be everything that is required to pull all the dependencies. No extra steps are needed. This is the [build script for linux/max/iOS](https://github.com/DiligentGraphics/DiligentCore/blob/master/BuildTools/Scripts/travis/build_install.sh) and this is the one for [windows](https://github.com/DiligentGraphics/DiligentCore/blob/master/appveyor.yml#L70).

**Comment by markusgod** [comment]
Yes, that one of possible ways, but to be included to conan-central-index and prevent re-including dependencies from multiple sources (like ImGui /stb/zlib), they require conan to do most of heavy lifting.

**Comment by TheMostDiligent** [comment]
The reason I prefer to include everything as submodules is because I can lock to some commits and guarantee that the codebase is in a good state and that everything will compile and run fine.
I can't count the number of times when I tried to build a project and it failed because it went out of sync with its third-party dependencies.

**Comment by markusgod** [comment]
I understand, there is no changes required from your side. It just would be nice if you can check and say "this library only required by samples, this is required by core". conan community will create and maintain package.

**Comment by TheMostDiligent** [comment]
I can certainly do that, I was just trying to understand how Conan works as I've never used it. It just seemed to me that manually listing all the dependencies is a lot extra unnecessary work when all that needs to be done is just cloning the repo recursively.

**Comment by markusgod** [comment]
For end user its just a matter of creating conanfile.txt and running `conan install .`
```conanfile.txt
[requires]
glfw/3.3.2@bincrafters/stable # some other lib that user needs independently of Diligent
DiligentEngine/v2.4.e # will pull diligent and all its dependencies automatically.
ExmapleLib/version@user/channel # @user/channel in not required in case of central index

[generators]
cmake
```
```cmake
include(conanbuildinfo.cmake)
target_link_libraries(Target ${CONAN_LIBS}) # CONAN_LIBS is set by conan
```
I'm probably not the best person to describe process in detail or how conan works internally.

**Comment by AndreyMlashkin** [comment]
conan is a very useful tool if you are using many different dependencies, that have other dependencies.

For example, we are using Qt and OpenCv in our project and would also like to use Diligent.
All three have a dependency from zlib of a different version.
conan makes it possible to manage a build tree, meaning version upgrade and managing build flags (like static/dynamic linkage).

git submodules are not suitable for this.
