### ISSUE TITLE
Input lag

### ISSUE THREAD

**Issue by eleval** [DiligentGraphics/DiligentEngine#81]
Hello,

First of all great work on your API. It simplifies a hell lot of work while still remaining low level enough.

I have started using it a couple of days ago on my engine, switching from an inhouse DirectX 11 abstraction layer to it and I have noticed I'm getting a noticeable input lag whenever my frame rate is close to and below 60fps (my screen is a 60Hz one). I did not have this issue when using my own implementation and vsync is of course disabled.

I have been looking around, trying different things but I can't get rid of this input lag. I don't know what is causing it and graphics programming isn't exactly my top field (although I'm learning).

If you need more info let me know.

EDIT : I'm using the DirectX 11 Backend of DiligentEngine.

**Comment by TheMostDiligent** [comment]
Yes, I indeed can see the lag in samples (e.g. GLTF viewer) when VSync is on. Interestingly, there is no lag in OpenGL/Vulkan mode.
There apparently something with the swap chain presentation, but I can't find what exactly is wrong.
I use 2-buffer `DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL` swap chain. 
How do you create the swap chain and present in your app where you don't see the lag?

**Comment by eleval** [comment]
Thanks for your quick reply :)

I haven't checked if I had the issue with the other backends yet. In any case, this is the way I create the SwapChain in my previous implementation. (Removed the error checking & intermediate arguments for clarity)

```
DXGI_SWAP_CHAIN_DESC sd;
ZeroMemory(&sd, sizeof(sd));
sd.BufferCount = 2;
sd.BufferDesc.Width = width;
sd.BufferDesc.Height = height;
sd.BufferDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
sd.BufferDesc.RefreshRate.Numerator = 0;
sd.BufferDesc.RefreshRate.Denominator = 1;
sd.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
sd.OutputWindow = windowHandle;
sd.SampleDesc.Count = 1;
sd.SampleDesc.Quality = 0;
sd.Windowed = FALSE;

IDXGIFactory* dxgiFactory = nullptr;
CreateDXGIFactory(__uuidof(IDXGIFactory), (LPVOID*)&dxgiFactory);
dxgiFactory->CreateSwapChain(d3dDevice, &sd, &swapChain_);
dxgiFactory->MakeWindowAssociation(desc.windowHandle, 0);
```

**Comment by TheMostDiligent** [comment]
So you run with VSync off? That may be the reason why you don't see the lag. What if you `swapChain_->Present(1, 0);`?

Still, it is really strange that there is a lag in D3D11/D3D12, and there is no lag in GL/Vulkan.

**Comment by eleval** [comment]
Yeah, I'm running both builds with vsync off.

If I set the swap interval to 1 on my implementation, there's still no lag (which is surprising), but the framerate is obviously capped at 60fps.

**Comment by TheMostDiligent** [comment]
Yeah, honestly I don't know what is going on. I tried to create the swap chain with different flip modes, in both windowed/fullscreen modes and the lag is still there.

**Comment by eleval** [comment]
I'll try several things on my end, will let you know if I find anything.
Thanks for looking into the issue.

**Comment by TheMostDiligent** [comment]
@eleval Thanks. I use `CreateSwapChainForHwnd` instead of `CreateSwapChain`, but that should not make any difference.

**Comment by eleval** [comment]
I did a few investigations today like using a IDXGISwapChain1 instead of IDXGISwapChain in my implementation, creating the SwapChain with DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL and CreateSwapChainForHwnd and I wasn't able to reproduce the issue on my implementation.

I also tried to create the DiligentEngine's SwapChain using DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING and calling Present with DXGI_PRESENT_ALLOW_TEARING and the issue was still there.

However, after trying several things I noticed that the issue wasn't present in Debug builds but only in Release builds. But the weirdest part is, the issue is also gone in Release if I force D3D11_CREATE_DEVICE_DEBUG to be set. Setting D3D11_CREATE_DEVICE_DEBUG or not in Debug makes no difference however, the issue is simply not present there.

I'll keep digging and will let you know if I find anything else.

**Comment by TheMostDiligent** [comment]
Thanks for looking into this. On my machine (Windows 10 + NVidia 970 GTX) I can see the lag in both Debug and Release builds.

**Comment by eleval** [comment]
Probably for the same reason as with D3D11_CREATE_DEVICE_DEBUG, but I don't get any input lag if I launch with the DirectX Graphics Debugger within VS2019.

Still looking but no luck so far, and can't find much information on the internet :(
Will probably call it a day and look again tomorrow.

**Comment by eleval** [comment]
I finally found out what was the issue.

While converting my Engine from my DirectX 11 implementation to DiligentEngine, I changed the way a vertex buffer was updated for a SpriteBatch. I switched from a Map/Unmap combo to UpdateBuffer. I don't know why or how I came to do that but that was the source of all my problems. (I didn't know until now that there was a big difference either between Map/Unmap and UpdateSubresources, I'm still learning about Graphics programming).

In any case, after replacing it with a Map/Unmap combo, the issue is totally gone and I get the exact same input latency as before.

Sorry for opening an issue for a noob problem haha, I hope I didn't make you waste too much time on my issue. I sure did waste my own time but at least I did learn a few things haha.

As the issue is resolved on my end, I'm closing it.

**Comment by TheMostDiligent** [comment]
@eleval 
Yes, UpdateBuffer is typically slower than Map/Unmap and is not intended for frequent updates. This is strange though, and I can actually see the issue on my side though.
Can you try to run GLTF viewer, turn VSync on in the Adapters dialog and check the latency by rotating the model? In D3D11/D3D12 mode I can clearly feel the lag, but it works without lag in OpenGL/Vulkan mode.

**Comment by eleval** [comment]
Yeah I can confirm I have a huge input lag (~80ms) with vsync turned on for DirectX 11 & 12. Very little input lag when using OpenGL or Vulkan (33ms).

**Comment by TheMostDiligent** [comment]
OK, this should be reopened then. So you experimented with VSync off?
Can you try your D3D11 implementation with VSync on?

**Comment by eleval** [comment]
Yes, I have been doing my benchmarks & rendering tests with vsync off for now.

I tried my implementation with vsync on and I get ~45ms of latency.

**Comment by TheMostDiligent** [comment]
That is certainly better. Can you spot any difference in [swap chain initialization](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineD3DBase/include/SwapChainD3DBase.hpp#L204) with your version. Thanks for looking into this!

**Comment by eleval** [comment]
There were several as I was creating a IDXGISwapChain instead of a IDXGISwapChain1. But even after changing the way I was initializing it to match yours the input lag was still at 45ms.

However I just did try running my engine with vsync on using DiligentEngine and the latency is at a low 31ms.

**Comment by TheMostDiligent** [comment]
> However I just did try running my engine with vsync on using DiligentEngine (using DirectX 11 backend) and the latency is at a low 31ms.

So you mean it could be latency in the sample itself? But input handling is completely orthogonal to rendering backend. Why there is no lag in OpenGL/Vk, weird.

**Comment by eleval** [comment]
I'm checking the Latency using PresentMon, which should be independant of the input handling.

**Comment by eleval** [comment]
Oh, so calling SetMaximumFrameLatency fixed the issue for you?
I toyed with it in the sample but it didn't change anything in my tests.

**Comment by TheMostDiligent** [comment]
No, it is more complicated than that. It was required to create a swap chain `DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT` and the explicitly synchronize with the swap chain presentation. You can read more [here](https://docs.microsoft.com/en-us/windows/uwp/gaming/reduce-latency-with-dxgi-1-3-swap-chains) if you are interested.
In the sample apps, I added an option to control the frame latency in the adapters dialog. When setting to 1 frame, the latency goes as low as 15 ms in D3D12 full-screen mode. Windowed mode adds at least one extra frame of latency, and D3D11 can never go under 30 ms.

**Comment by eleval** [comment]
Ok, I see what you mean. I did read a bit about the waitable swapchain but didn't look more into it as didn't have any issue without it. I'll give it a deeper read.
Thanks for the indsight and good to know you were able to fix the issue :)
