### ISSUE TITLE
Platforms other than D3D12 not working.

### ISSUE THREAD

**Issue by VividCoder** [DiligentGraphics/DiligentEngine#82]
Hi,

If I use any platform other than D3D12 - even d3d11, It fails quite often, usually to do with graphics pipelines/shaders.

Is there something I  need to add for it to do the automatic shader conversion?

Is there any chance of a pre-built release for Windows platforms? I.e with support enabled properly?

The app works fine in D3D12 mode. Been trying all day to figure it out, but no luck.

**Comment by TheMostDiligent** [comment]
> It fails quite often

What is "it"? Do you mean samples/tutorials? If so, which ones exactly. All of them?

Please provide the information that the issue template asks you to provide:

- OS and version you are running (e.g. Windows 10.0.18362, MacOS Catalina 10.15, etc.)
- Build tools and configuration you used to build the engine (e.g. Visual Studio 2017 Debug x64 + CMake 3.15.4)
- GPU and driver version you have installed on your system
- Debug output, especially messages from Diligent
- Call stack (if available)


> Is there something I need to add for it to do the automatic shader conversion?

No, shader conversion is done automatically by the engine as described [here](https://github.com/DiligentGraphics/DiligentCore#creating-shaders)

> Is there any chance of a pre-built release for Windows platforms? I.e with support enabled properly?

As suggested [here](https://github.com/DiligentGraphics/DiligentEngine#your-project-does-not-use-cmake), you can download the latest binaries for Windows from [appveyor](https://ci.appveyor.com/project/DiligentGraphics/diligentcore).

> The app works fine in D3D12 mode.

What app??

**Comment by VividCoder** [comment]
Sorry, I tried appveyor and it seems to be working, thanks.
