### ISSUE TITLE
VSync off not working in Windowed D3D11

### ISSUE THREAD

**Issue by lenny93** [DiligentGraphics/DiligentEngine#83]
Thank you for this amazing library. Only issue I have found so far is that switching vsync off in windowed d3d11 mode does not work, in either none of the demos or my own app (using Present(0) and otherwise). Setting vsync off works in d3d11 fullscreen as well as all the other backends. I had this issue from a version released last week (my first time using Diligent) and just updated to the last commit regarding #81 but the problem is still there (it's funny because I've been trying to solve this issue and I thought it was probably a swap chain setup issue, also reading online about differences between DXGI interface versions but then I found that new commit.)

Also, I wasn't sure whether to open a different issue (because I thought it was obvious and probably intentional) but the color handling in the Imgui demo (at least) is wrong. Using an SRGB color buffer fixes that problem.

**- OS and version you are running (e.g. Windows 10.0.18362, MacOS Catalina 10.15, etc.)** Windows 10.0.14393
**- Build tools and configuration you used to build the engine (e.g. Visual Studio 2017 Debug x64 + CMake 3.15.4)** VS 2017 Debug/Release x64
**- Debug output, especially messages from Diligent** N/A
**- If you experience a problem with one back-end, please try running other back-ends and see if the same issue arises** Only DX11 windowed

**Comment by TheMostDiligent** [comment]
Can you try to run one of [directx sdk samples](https://github.com/walbourn/directx-sdk-samples) (e.g. [fluids simulation](https://github.com/walbourn/directx-sdk-samples/tree/master/FluidCS11)) and see if VSync off works? You windows version seem to be little old, this may be the reason too.

Yes, I know about sRGB issue in imgui. Did not have time to fix it yet.

**Comment by lenny93** [comment]
Thanks for the quick reply. And yes, it works in the directx samples:
![image](https://user-images.githubusercontent.com/1112924/82525447-a5a26a00-9aee-11ea-8d73-34d0996c655e.png)

**Comment by TheMostDiligent** [comment]
TBH, I don't know. It works fine on my Intel HD 4600 GPU in windowed mode. I though that it might be related to the waitable swap chain, but you said it was like that before the change too. The fact that it works in full-screen mode also makes this really odd.

**Comment by lenny93** [comment]
Update: it works with the dedicated graphics card. For some reason it's just not working with the Intel (and in Diligent only). It's not that big of an issue but since most laptops have Intel GPUs I'll keep looking for a fix.

**Comment by TheMostDiligent** [comment]
OK, thanks. I suspect this is either driver or Windows issue. The fact that this works with discrete GPU is a very strong indicator. I would recommend updating everything to the latest as the very first step.
As a note, that would be a real problem if it did not work with VSync on as real applications should not run with VSync off.

**Comment by lenny93** [comment]
Yup, I agree about that. I simply wanted to disable Vsync to measure performance, but obviously in client scenarios one would suggest to leave it on.

**Comment by TheMostDiligent** [comment]
Try to update the driver. This very often fixes weird problems
