### ISSUE TITLE
How to use XSurface to create a vulkan backend

### ISSUE THREAD

**Issue by carlcc** [DiligentGraphics/DiligentEngine#85]
Hi,

I'm trying to use [gainput](https://github.com/jkuhlmann/gainput) as input manager (writing a cross platform input manager is a lot of work, I don't want to do that).

But unfortunately gainput has not implemented xcb backend(only Xlib backend is available), while it seems that diligent engine has not implemented XSurface backend.

I have tried 2 methods to solve this problem, but failed:

1. Convert xcb_event to XEvent (Create a fake XEvent)

2. Add xcb_event back end into gainput. 

Both these solutions are much complex than it seems to be.

So I'm here to ask for help, wondering the cost to make diligent engine support XSurface.

Regards.

**Comment by TheMostDiligent** [comment]
Enabling xlib support in Vulkan should not be a big issue, will take a look.

**Comment by carlcc** [comment]
Thanks a lot!

**Comment by TheMostDiligent** [comment]
@carlcc To initialize Vulkan using XLib surface, you will need to initialize [pDisplay](https://github.com/DiligentGraphics/DiligentCore/blob/master/Platforms/Linux/interface/LinuxNativeWindow.h#L38) plus `WindowId` instead of `pXCBConnection`.
