### ISSUE TITLE
How to synchronize after flush

### ISSUE THREAD

**Issue by llagardeOSE** [DiligentGraphics/DiligentEngine#87]
Hi, 

My application needs to post-process the rendering results with some GPU kernels written in CUDA.
In order to do that I:
- set up a render target
- record the rendering commands
- flush the device context
- synchronize the rendering in order to ensure the render target is ready
- launch the CUDA kernels with signal input == render target, output == current swap chain color image
- present the rendered image

I use the Vulkan rendering back-end.

My question is: how to properly synchronize the 2 passes?
Right now I have modified diligent to make public the fence value and the fence queue used when submitting the commands. So I can wait for fence value to be popped from the fence queue.
In order to do that I had to access to the private interface (include). I think I should not do that.

Lionel Lagarde

**Comment by TheMostDiligent** [comment]
Hi! Can you clarify what kind of synchronization you need to do? Is it GPU-CPU synchronization or a GPU-GPU one? From what you described it seems like you may need a GPU-GPU barrier to transition from CUDA output state to maybe shader resource state? For this, there is [IDeviceContext::TransitionResourceStates](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/DeviceContext.h#L1305)

For GPU-CPU synchronization there are multiple ways:
1. Use [Fences](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/Fence.h#L62). The fence is a common API object implemented in all backends. It has [GetCompletedValue](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/Fence.h#L62) that allows querying current fence value, so I am not sure which exactly interface you modified and how it is different from the fence implementation.
2. Use [IDeviceContext::WaitForFence](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/DeviceContext.h#L1067) to block CPU until the fence is signaled.
3. Use [IDevice::IdleGPU](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/RenderDevice.h#L234) to Idle the GPU.
4. Use [IDevlceContext::WaitForIdle](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/DeviceContext.h#L1081) to idle the context's internal command queue.

**Comment by llagardeOSE** [comment]
Yes it is for a GPU-CPU synchronization I am looking for.

I have looked at the fence interface and the related device context interface and I cannot figure out how to:
- get the IFence object the device context is using
- get the fence value so I can wait for it

**Comment by TheMostDiligent** [comment]
You do not get the fence from the context, instead, you create it like any other device object using [IRenderDevice::CreateFence](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/RenderDevice.h#L174). Then you [signal the fence](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/DeviceContext.h#L1043) in the device context and [check its completed value](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/Fence.h#L74) or [wait for it](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/DeviceContext.h#L1067). 
Like I mentioned, if you simply need to wait for GPU to complete all operations, you can use [IDevlceContext::WaitForIdle](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/DeviceContext.h#L1081).

**Comment by llagardeOSE** [comment]
There is something I don't get.

In the sequence of operations you describe, no operations says "please GPU, when you have finished executing the commands, signal this VkFence". AFAIK the only way to do that is vkQueueSubmit.

Maybe wait for idle is the way to go.

**Comment by TheMostDiligent** [comment]
> please GPU, when you have finished executing the commands, signal this VkFence

This is exactly what [IDeviceContext::SignalFence](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/DeviceContext.h#L1033) does. This is from the method description:

` ` ` 
Tells the GPU to set a fence to a specified value after all previous work has completed.
` ` `

**Comment by llagardeOSE** [comment]
I think I get it now.
Calling IDeviceContext::SignalFence before flush makes the device context to call vkQueueSubmit with no submit info but a VkFence to be signaled. The empty submit is done after the draw submit. Calling wait for fence the same value as the submit one will do the job.

Sorry for the noise.

**Comment by TheMostDiligent** [comment]
> Calling IDeviceContext::SignalFence before flush makes the device context to call vkQueueSubmit with no submit info but a VkFence to be signaled. The empty submit is done after the draw submit.

Not exactly. The fences are queued and added to the next `vkQueueSubmit` command, whether implicit or explicit via `Flush`. The method description explains that too:

```
The method does not flush the context (an application can do this explcitly if needed)
and the fence will be signaled only when the command context is flushed next time.
If an application needs to wait for the fence in a loop, it must flush the context
after signalling the fence.
```
You can check the API documentation in the comments, it should give answers to many questions.

Closing this issue as your question seems to be resolved, but feel free to reopen.
