### ISSUE TITLE
How to allocate GPU memory using different options

### ISSUE THREAD

**Issue by llagardeOSE** [DiligentGraphics/DiligentEngine#88]
Hi, 

I use the Vulkan back-end.
I use the CUDA / Vulkan interoperability.

In order to make the GPU memory allocated by diligent visible from CUDA, with Vulkan, I need to use the extension mechanism.

The VkMemoryAllocateInfo is chained with the VkExportMemoryWin32HandleInfoKHR and the VkExportMemoryAllocateInfoKHR structures.

I need to pass the relevant information down to the VulkanMemoryManager from a texture interface (in my case).
I also need the VulkanMemoryManager to allocate a dedicated page.

Right now I allocate all the GPU memory using the export options (I don't know what it means for staging memory).

What is the preferred way to pass allocation options/data down to the memory allocator of the back-end?

**Comment by TheMostDiligent** [comment]
VulkanMemoryManager is a Vulkan-specific implementation detail and so it is not exposed in the public API. For your purposes, will it be feasible to create the texture in your application using raw Vulkan and then attach it to Diligent texture using [CreateTextureFromVulkanImage](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/interface/RenderDeviceVk.h#L90)? At this point there is no mechanism in the API to customize memory allocation when a resource is created.

**Comment by llagardeOSE** [comment]
I understand, but the thing I am looking for is CreateMemoryPageFromVulkanMemoryAllocation.

**Comment by TheMostDiligent** [comment]
Well, like I said, `VulkanMemoryManager` is very implementation-specific. Its internal operation may change, or it may be replaced altogether without changing the public API. I don't think there is a way to elegantly exposed it in the API.
In your very specific case it seems like attaching Vulkan image to Diligent Texture is the better way to go. Why does it not work for you?
