### ISSUE TITLE
Replace GLEW with GLAD

### ISSUE THREAD

**Issue by Pitj3** [DiligentGraphics/DiligentEngine#92]
Is it possible to replace GLEW with GLAD?

I'm running my project with GLAD and would like to use Diligent in it, but combining GLEW and GLAD is a big no no.

**Comment by TheMostDiligent** [comment]
It is likely possible. You will need to replace `glew.h` with `glad.h` e.g. [here](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineOpenGL/include/pch.h#L47) (you did not fill the template, and I don't know which platform you are on so I default to Windows), and replace `glewInit` with `gladLoadGL` [here](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineOpenGL/src/GLContextWindows.cpp#L188).

Besides, if you build the engine as dynamic library, there will be no conflict between GLEW and GLAD.

**Comment by Pitj3** [comment]
Do I have to supply any specific settings to build the engine as dynamic? I can't find it on the build readme

**Comment by TheMostDiligent** [comment]
It builds both static and dynamic versions, you can choose which target you want to link against, e.g. `Diligent-GraphicsEngineOpenGL-static` vs `Diligent-GraphicsEngineOpenGL-dynamic`
