### ISSUE TITLE
Availability of standalone samples

### ISSUE THREAD

**Issue by GPUCode** [DiligentGraphics/DiligentEngine#94]
To begin with, I have to say this is an awesome framework. I want to make a cross platform graphics application where the user has the option of switching between multiple graphics backends, so I thought this project is currently the most mature and best one. Keep in mind that the API is completely alien to me, after some time of exclusive use of OpenGL 3.3+. The samples are really helpful overall, but I found them useless as they derive from SampleBase which provides many helper methods like (Initialize, Update, Render) and matrix operations. The only sample I could work on was the Win32 Hello Triangle example, which unforunately hardcodes the vertices in the vertex shader. For the past couple of days I have been trying to adapt it to GLFW + Vertex Buffers with code from the Cube example to no avail. My questions are:

1. Is there any possibility of translating some of the examples to be more like the first standalone one ?
2. Is there any debugging utility in Diligent that allows to find errors in the code/shaders?

Thanks

**Comment by TheMostDiligent** [comment]
The goal of the tutorials is to show how to use the graphics API, not how to handle user input or perform any other platform-specific tasks which are orthogonal to the API and are provided by the framework. The two standalone tutorials for Windows and Linux show how to setup the application from ground up. If you want to convert e,g Tutorial 02 into a standalone, you can easily copy all the contents from `Tutorial02_Cube.cpp` to `Tutorial00_HelloTriangle.cpp`. There are the same `Update` and `Render` functions. Having window initialization code in every tutorial will obscure the goal of demonstrating the API usage.

As to debugging, Diligent performs a lot of validation and prints warnings/errors to debug output. Second, you can use standard tools like RenderDoc, Microsoft PIX, or tools from NVidia/AMD for shader profiling and debugging.
