### ISSUE TITLE
DX11 + IDXGISwapChain2 not able to be used on win7 systems.

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentEngine#95]
In recent adjustments for https://github.com/DiligentGraphics/DiligentEngine/issues/81, it seems IDXGISwapChain2 is now used by default on dx11 backend. For win7 system, it seems [this is not supported](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_3/nn-dxgi1_3-idxgiswapchain2). I wonder if some workaround could be provided so programs can still support win 7?

The related commit is: https://github.com/DiligentGraphics/DiligentCore/commit/64888e8097027b9becb6ab4def09b510d291cf64

**Comment by TheMostDiligent** [comment]
Does it fail to query the `IDXGISwapChain2` interface [here](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineD3DBase/include/SwapChainD3DBase.hpp#L257)?

**Comment by crlf0710** [comment]
@TheMostDiligent Yes, exactly!

**Comment by crlf0710** [comment]
Thanks!

**Comment by TheMostDiligent** [comment]
Let me know if this doesn't work.
