### ISSUE TITLE
any plane for support mesh shader?

### ISSUE THREAD

**Issue by 9MW** [DiligentGraphics/DiligentEngine#96]

**Comment by TheMostDiligent** [comment]
In fact, there is a plan. Mesh shaders should be enabled soon.

**Comment by 9MW** [comment]
good to head that

**Comment by TheMostDiligent** [comment]
FYI, questions like this are usually easier to discuss on [Gitter](https://gitter.im/diligent-engine) or [Discord](https://discord.gg/t7HGBK7)
