### ISSUE TITLE
Gltfview bug

### ISSUE THREAD

**Issue by 9MW** [DiligentGraphics/DiligentEngine#97]
render random triangle while load https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/Soldier.glb

**Comment by TheMostDiligent** [comment]
I can reproduce the issue with the model. It would be great to have a simpler reproducer to understand what GLTF feature causes the problem.

**Comment by 9MW** [comment]
just load random model to check robustbility,have no idea what's causes the problem

**Comment by crlf0710** [comment]
Didn't investigate into the file, but from the description it should be the primitive mode problem. Currently the loader and renderer assumes every primitive is using mode 4 (triangles) but in reality there are dots and lines and strips and fans and so on.

**Comment by TheMostDiligent** [comment]
@crlf0710 Thanks for the hint, but apparently all (two) primitives in the model use mode 4. They also use 6 different texture coordinate sets, so this may be the reason, I did not find out yet.

**Comment by TheMostDiligent** [comment]
![image](https://user-images.githubusercontent.com/61806567/94094330-1080ec00-fdd4-11ea-98de-d72fc9fb9f28.png)
