### ISSUE TITLE
link error when build tutorial12 on iOS platform on Mac 10.15

### ISSUE THREAD

**Issue by youZhuang** [DiligentGraphics/DiligentEngine#99]
OS : MacOS Catalina 10.15
Xcode 11.4 CMake 3.15.3
AMD

build log:
`ld: warning: ignoring file /usr/local/opt/llvm@8/lib/libc++.dylib, building for iOS-arm64 but attempting to link with file built for macOS-x86_64
ld: in '/usr/local/opt/llvm@8/lib/libunwind.dylib', building for iOS-arm64 but attempting to link with file built for macOS-x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by TheMostDiligent** [comment]
Can you try the command as recommended [in this section](https://github.com/DiligentGraphics/DiligentEngine#ios):
```
cmake -DCMAKE_TOOLCHAIN_FILE=DiligentCore/ios.toolchain.cmake -DIOS_PLATFORM=OS64 -H. -Bbuild/IOS -GXcode
```

**Comment by youZhuang** [comment]
I installed a custom llvm,uninstalled it and resolved it.
